import { person } from '../speakers/speaker';

export const teams: person[] = [
  // {
  //   index: 0,
  //   name: 'Isreal Aluko',
  //   jobTitle: 'Software Engineer',
  //   employer: '',
  //   image: 'https://ibb.co/kgs3gXsX',
  // },
  // {
  //   index: 1,
  //   name: 'Zainab Tijani',
  //   jobTitle: 'Software Developer',
  //   employer: 'PressOne.',
  //   image: 'https://ibb.co/7t7bNP7Y',
  // },
  // {
  //   index: 2,
  //   name: 'Bello Kareem',
  //   jobTitle: 'Data annotator',
  //   employer: 'Hugoinc',
  //   image: 'https://ibb.co/0VRFq80g',
  // },
  // {
  //   index: 3,
  //   name: 'Idris Olubisi',
  //   jobTitle: 'Developer Relations Engineer',
  //   employer: '',
  //   image: 'https://ibb.co/Kcq7wYRF',
  // },
  // {
  //   index: 4,
  //   name: 'Oriji Onyinyechi Sandra',
  //   jobTitle: 'Data Analyst/Scientist',
  //   employer: '',
  //   image: 'https://ibb.co/bjChygkP',
  // },
  // {
  //   index: 5,
  //   name: 'Claret Ibeawuchi',
  //   jobTitle: 'AI-Native Fullstack Engineer',
  //   employer: '',
  //   image: 'https://ibb.co/1J4FHX2B',
  // },
  // {
  //   index: 6,
  //   name: 'Victoria Nduka',
  //   jobTitle: 'User Experience Designer',
  //   employer: '',
  //   image: 'https://ibb.co/r24nRX2d',
  // },
  // {
  //   index: 7,
  //   name: 'Sule-balogun Olanrewaju',
  //   jobTitle: 'Software Engineer',
  //   employer: '@ Tillo',
  //   image: 'https://ibb.co/Mk4MzN3X',
  // },
  // {
  //   index: 8,
  //   name: 'Joshua Omobola',
  //   jobTitle: 'Developer Relations Engineer',
  //   employer: '',
  //   image: 'https://ibb.co/LXWYYBQj',
  // },
  // {
  //   index: 9,
  //   name: 'Marvis Chukwudi',
  //   jobTitle: 'Content Executive',
  //   employer: '@Sterling Bank',
  //   image: 'https://ibb.co/zVLXSr83',
  // },
  // {
  //   index: 10,
  //   name: 'Peculiar Abolade',
  //   jobTitle: 'Software Developer',
  //   employer: 'Zijela ICT',
  //   image: 'https://ibb.co/nNyTchgF',
  // },
  // {
  //   index: 11,
  //   name: 'Adekunle Abdul-Roqeeb',
  //   jobTitle: 'UI Designer',
  //   employer: '',
  //   image: 'https://ibb.co/4nKYQZ2J',
  // },
  // {
  //   index: 12,
  //   name: 'Oluwadamilola Oshungboye',
  //   jobTitle: 'Software Engineer',
  //   employer: '@ SeamlessHR',
  //   image: 'https://ibb.co/hRr40cS7',
  // },
  // {
  //   index: 13,
  //   name: 'Sherifat Ajoke Omitogun',
  //   jobTitle: 'Web/Frontend Developer',
  //   employer: '',
  //   image: 'https://ibb.co/bgdd7Y45',
  // },
  // {
  //   index: 14,
  //   name: 'Williams Eni',
  //   jobTitle: 'Designer',
  //   employer: '',
  //   image: 'https://ibb.co/HDLkBvtJ',
  // },
  // {
  //   index: 15,
  //   name: 'Tama Ebiere Thoro',
  //   jobTitle: 'Product Manager',
  //   employer: '',
  //   image: 'https://ibb.co/C3WSh7QH',
  // },
  // {
  //   index: 16,
  //   name: 'Emmanuel Jemeni',
  //   jobTitle: 'Frontend Developer',
  //   employer: '',
  //   image: 'https://ibb.co/cKpYfHSt',
  // },
  // {
  //   index: 17,
  //   name: 'Irene Dyboh',
  //   jobTitle: 'Young Professional (YP)',
  //   employer: 'NNPC Limited',
  //   image: 'https://ibb.co/d4b6wPvs',
  // },
  // {
  //   index: 18,
  //   name: 'Victor Okoye',
  //   jobTitle: 'Software Engineer',
  //   employer: '',
  //   image: 'https://ibb.co/kdsBZSD',
  // },
  {
    index: 19,
    name: 'Grace Effiong',
    jobTitle: 'Frontend Software Developer',
    employer: 'Lotus bank',
    image: 'https://i.ibb.co/WNKPZTMB/passport2.jpg',
  },
];
