import { person } from '../speakers/speaker';

export const teams: person[] = [
  {
    index: 0,
    name: 'Isreal Aluko',
    jobTitle: 'Software Engineer',
    employer: '',
    image: 'https://i.ibb.co/tMN1yjs7/20250629-133702.jpg',
  },
  {
    index: 1,
    name: 'Zainab Tijani',
    jobTitle: 'Software Developer',
    employer: 'at PressOne.',
    image: 'https://i.ibb.co/XxmVk1m2/zainab-s-new-dp.jpg',
  },
  {
    index: 2,
    name: 'Bello Kareem',
    jobTitle: 'Data annotator',
    employer: 'hugoinc',
    image: '/teams/kareem.jpg',
  },
  {
    index: 3,
    name: 'Oriji Onyinyechi Sandra',
    jobTitle: 'Data Analyst/Scientist',
    employer: '',
    image: 'https://i.ibb.co/BHQD7V9t/photo.jpg',
  },
  {
    index: 4,
    name: 'Claret Ibeawuchi',
    jobTitle: 'AI-Native Fullstack Engineer',
    employer: '',
    image: 'https://i.ibb.co/0VzHP9J1/IMG-4832.jpg',
  },
  {
    index: 5,
    name: 'Victoria Nduka',
    jobTitle: 'User Experience Designer',
    employer: '',
    image: 'https://i.ibb.co/KxFCp8xK/IMG-6786.jpg',
  },
  {
    index: 6,
    name: 'Marvis Chukwudi',
    jobTitle: 'Content Executive',
    employer: 'Sterling Bank',
    image: 'https://i.ibb.co/yFM68Xhz/PXL-20250506-065120968-2.jpg',
  },
  {
    index: 7,
    name: 'Adekunle Abdul-Roqeeb',
    jobTitle: 'UI Designer',
    employer: '',
    image: 'https://i.ibb.co/rRFcWG3v/hh.png',
  },
  {
    index: 8,
    name: 'Oluwadamilola Oshungboye',
    jobTitle: 'Software Engineer',
    employer: 'SeamlessHR',
    image: 'https://i.ibb.co/6RGTQ8kn/Dami-s-Potrait.jpg',
  },
  {
    index: 9,
    name: 'Sherifat Ajoke Omitogun',
    jobTitle: 'Web/Frontend Developer',
    employer: '',
    image: 'https://i.ibb.co/GvPPFGZQ/IMG-20221117-WA0004.jpg',
  },
  {
    index: 10,
    name: 'Williams Eni',
    jobTitle: 'Designer',
    employer: '',
    image: 'https://i.ibb.co/Z6RkGsBZ/IMG-9269.jpg',
  },
  {
    index: 11,
    name: 'Michael Ibikunle',
    jobTitle: 'SOC Analyst',
    employer: '',
    image: 'https://i.ibb.co/VY8DfYgM/Headshot.jpg',
  },
  {
    index: 12,
    name: 'Micah Timileyin',
    jobTitle: 'Program Manager',
    employer: '',
    image: 'https://i.ibb.co/ycmznrQ3/hh.jpg',
  },
  {
    index: 13,
    name: 'Emmanuel Olubiyi',
    jobTitle: 'Software Engineer | IT (intern)',
    employer: 'Meristem',
    image: 'https://res.cloudinary.com/dmhqnusvw/image/upload/v1751812098/pfp_vdbwcs.jpg',
  },
  {
    index: 14,
    name: 'Gbadebo Bello',
    jobTitle: 'Developer Advocate',
    employer: 'Postman',
    image: 'https://i.ibb.co/7JNfBCwh/Dev-Fest-23-30-2.jpg',
  },
  {
    index: 15,
    name: 'Sodiq Akinjobi',
    jobTitle: 'Program Manager',
    employer: '',
    image: '/teams/sodiq.png',
  },
  {
    index: 16,
    name: 'Kruse',
    jobTitle: 'Senior Software Engineer',
    employer: '',
    image: '/teams/kruse.jpg',
  },
];
