import { person } from '../speakers/speaker';

export const teams: person[] = [
  {
    index: 0,
    name: 'Isreal Aluko',
    jobTitle: 'Software Engineer',
    employer: '',
    image: 'https://i.ibb.co/tMN1yjs7/20250629-133702.jpg',
  },
  {
    index: 1,
    name: 'Zainab Tijani',
    jobTitle: 'Software Developer',
    employer: 'at PressOne.',
    image: 'https://i.ibb.co/XxmVk1m2/zainab-s-new-dp.jpg',
  },
  {
    index: 2,
    name: 'Bello Kareem',
    jobTitle: 'Data annotator',
    employer: 'hugoinc',
    image: 'https://i.ibb.co/dJwLB1Nd/93ad1f70-3d9c-4aa5-b762-6a49f9ff62d1.jpg',
  },
  {
    index: 3,
    name: 'Idris Olubisi',
    jobTitle: 'Developer Relations Engineer',
    employer: '',
    image: 'https://i.ibb.co/nqcfCTZz/Idris-Olubisi-headshot.jpg',
  },
  {
    index: 4,
    name: 'Oriji Onyinyechi Sandra',
    jobTitle: 'Data Analyst/Scientist',
    employer: '',
    image: 'https://i.ibb.co/BHQD7V9t/photo.jpg',
  },
  {
    index: 5,
    name: 'Claret Ibeawuchi',
    jobTitle: 'AI-Native Fullstack Engineer',
    employer: '',
    image: 'https://i.ibb.co/0VzHP9J1/IMG-4832.jpg',
  },
  {
    index: 6,
    name: 'Victoria Nduka',
    jobTitle: 'User Experience Designer',
    employer: '',
    image: 'https://i.ibb.co/KxFCp8xK/IMG-6786.jpg',
  },
  {
    index: 7,
    name: 'Sule-balogun Olanrewaju',
    jobTitle: 'Software Engineer',
    employer: 'Tillo',
    image: 'https://i.ibb.co/YBMp5jqr/WhatsApp-Image-2024-04-21-at-23-47-06.jpg',
  },
  {
    index: 8,
    name: 'Joshua Omobola',
    jobTitle: 'Developer Relations Engineer',
    employer: '',
    image: 'https://i.ibb.co/tTtQQnZj/IMG-9012.jpg',
  },
  {
    index: 9,
    name: 'Marvis Chukwudi',
    jobTitle: 'Content Executive',
    employer: 'Sterling Bank',
    image: 'https://i.ibb.co/yFM68Xhz/PXL-20250506-065120968-2.jpg',
  },
  {
    index: 10,
    name: 'Peculiar Abolade',
    jobTitle: 'Software Developer',
    employer: 'Zijela ICT',
    image: 'https://i.ibb.co/sd4hwLmZ/VS-0561.jpg',
  },
  {
    index: 11,
    name: 'Adekunle Abdul-Roqeeb',
    jobTitle: 'UI Designer',
    employer: '',
    image: 'https://i.ibb.co/rRFcWG3v/hh.png',
  },
  {
    index: 12,
    name: 'Oluwadamilola Oshungboye',
    jobTitle: 'Software Engineer',
    employer: 'SeamlessHR',
    image: 'https://i.ibb.co/6RGTQ8kn/Dami-s-Potrait.jpg',
  },
  {
    index: 13,
    name: 'Sherifat Ajoke Omitogun',
    jobTitle: 'Web/Frontend Developer',
    employer: '',
    image: 'https://i.ibb.co/GvPPFGZQ/IMG-20221117-WA0004.jpg',
  },
  {
    index: 14,
    name: 'Williams Eni',
    jobTitle: 'Designer',
    employer: '',
    image: 'https://i.ibb.co/Z6RkGsBZ/IMG-9269.jpg',
  },
  {
    index: 15,
    name: 'Tama Ebiere Thoro',
    jobTitle: 'Product Manager',
    employer: '',
    image: 'https://i.ibb.co/cSxsDFQr/IMG-4192.jpg',
  },
  {
    index: 16,
    name: 'Emmanuel Jemeni',
    jobTitle: 'Frontend Developer',
    employer: '',
    image: 'https://i.ibb.co/Cs8CXLD8/20240622-155819-crop-1.jpg',
  },
  {
    index: 17,
    name: 'Irene Dyboh',
    jobTitle: 'Product Manager ',
    employer: '',
    image: 'https://i.ibb.co/Xxypr7Pf/IMG-5127.jpg',
  },
  // {
  //   index: 18,
  //   name: 'Victor Okoye',
  //   jobTitle: 'Software Engineer',
  //   employer: '',
  //   image: 'https://i.ibb.co/79dCh1p/IMG-2244.jpg',
  // },
  {
    index: 19,
    name: 'Grace Effiong',
    jobTitle: 'Frontend Software Developer',
    employer: 'Lotus bank',
    image: 'https://i.ibb.co/WNKPZTMB/passport2.jpg',
  },
  // {
  //   index: 20,
  //   name: 'Ugochukwu Egeonu',
  //   jobTitle: 'Software Engineer',
  //   employer: 'Jointly',
  //   image: 'https://i.ibb.co/JFtLt9Rw/IMG-3933.jpg',
  // },
  {
    index: 21,
    name: 'Michael Ibikunle',
    jobTitle: 'SOC Analyst',
    employer: '',
    image: 'https://i.ibb.co/VY8DfYgM/Headshot.jpg',
  },
  {
    index: 22,
    name: 'Ehimwenman Edemakhiota',
    jobTitle: 'Software Engineer',
    employer: 'Interswitch',
    image:
      'https://i.ibb.co/kVXSKmGb/AP1-Gcz-Mc-EVMLYHQMbj8-Dptr9ovuv-Rivi-BIf88-Eva-Zk-U4-Jqgtj4-KYb-R8-PIg-Sx-OYw-HWBr-DXimsjeo-d-D6-BQ.jpg',
  },
  {
    index: 23,
    name: 'Micah Timileyin',
    jobTitle: 'Program Manager',
    employer: '',
    image: 'https://i.ibb.co/ycmznrQ3/hh.jpg',
  },
  {
    index: 24,
    name: 'Emmanuel Olubiyi',
    jobTitle: 'Software Engineer | IT (intern)',
    employer: 'Meristem',
    image: 'https://res.cloudinary.com/dmhqnusvw/image/upload/v1751812098/pfp_vdbwcs.jpg',
  },
  {
    index: 25,
    name: 'Gbadebo Bello',
    jobTitle: 'Developer Advocate',
    employer: 'Postman',
    image: 'https://i.ibb.co/7JNfBCwh/Dev-Fest-23-30-2.jpg',
  },
  {
    index: 26,
    name: 'Sodiq Akinjobi',
    jobTitle: 'Program Manager',
    employer: '',
    image: '/teams/sodiq.png',
  },
  {
    index: 26,
    name: 'Osuji Prince Victory',
    jobTitle: 'FrontEnd Developer | Videography and Creative Intern ',
    employer: '',
    image: 'https://i.ibb.co/DPXSR171/img-2-1733419695512.webp',
  },
  {
    index: 26,
    name: 'Kruse',
    jobTitle: 'Senior Software Engineer',
    employer: '',
    image: '/teams/kruse.jpg',
  },
  {
    index: 26,
    name: 'Ajiboye Toluwanimi Elijah',
    jobTitle: 'Social Media Manager',
    employer: 'Web3 Global Conference LLC',
    image: '/teams/tolu.jpg',
  },
];
