export const scheduleData = {
  title: 'Your Day at a Glance',
  days: [
    {
      dayNumber: 1,
      date: 'Fri 18 Jul',
      sessions: [
        {
          id: 'check-in-fri',
          title: 'Check-in',
          timeSlot: '08:00am - 09:30am',
          room: 'Ruby Hall',
          duration: '1hr 30m',
          timeFrame: '8am',
          type: 'Check-in',
          color: '#D9D9D9',
        },
        {
          id: 'welcome-address-fri',
          title: 'Welcome address',
          timeSlot: '09:30am - 10:00am',
          room: 'Ruby Hall',
          duration: '30m',
          timeFrame: '9am',
          type: 'Welcome',
          color: '#D9D9D9',
        },
        {
          id: 'building-to-last-fri',
          title: 'Building to last',
          timeSlot: '10:00am - 10:15am',
          room: 'Ruby Hall',
          duration: '15m',
          timeFrame: '10am',
          type: 'Keynote',
          speaker: 'Michael Owolabi',
          color: '#ECC89D',
        },
        {
          id: 'from-frustration-to-flow-creating-api-documentation-developers-actually-love-fri',
          title: 'From Frustration to Flow: Creating API Documentation Developers Actually Love',
          timeSlot: '10:15am - 10:30am',
          room: 'Ruby Hall',
          duration: '15m',
          timeFrame: '10am',
          type: 'Keynote',
          speaker: 'Chisom Uma',
          color: '#ECC89D',
        },
        {
          id: 'host-announcement-fri',
          title: 'Host announcement',
          timeSlot: '10:30am - 10:35am',
          room: 'Ruby Hall',
          duration: '5m',
          timeFrame: '10am',
          type: 'Anouncement',
          color: '#D9D9D9',
        },
        {
          id: 'google-codelab-sat',
          title: 'Going Multimodal with Agent Development Kit: Personal Expense Assistant with Gemini 2.5',
          timeSlot: '10:35am - 11:30pm',
          room: 'Emerald Hall',
          duration: '45m',
          timeFrame: '10am',
          type: 'workshop',
          speaker: 'Sikiru Abidemi Tiamiyu',
          color: '#E1EF9A',
        },
        {
          id: 'building-apis-on-cloudflare-fri',
          title: 'Building APIs on cloudflare',
          timeSlot: '10:35am - 10:45am',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '10am',
          type: 'Lightning',
          speaker: 'Daniel Benjamin',
          color: '#90EAF2',
        },
        {
          id: 'api-architecure-fri',
          title: 'API Architecure',
          timeSlot: '10:45am - 10:55am',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '10am',
          type: 'Lightning',
          speaker: 'Echezona Agubata',
          color: '#90EAF2',
        },
        {
          id: 'morning-coffee/break-fri',
          title: 'Networking Break',
          timeSlot: '10:55am - 11:20am',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '10am',
          type: 'Coffee/Break',
          color: '#D9D9D9',
        },
        {
          id: 'api-engineering-at-mono-scaling-microservices-to-handle-millions-of-requests-per-month-fri',
          title:
            'API Engineering at Mono: Scaling Microservices to Handle Millions of Requests per Month',
          timeSlot: '11:20am - 11:45am',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '11am',
          type: 'session',
          speaker: 'Betty Alagwu',
          color: '#E1EF9A',
        },
        {
          id: 'why-your-api-is-making-frontend-developers’-lives-harder-(and-how-to-fix-it)-fri',
          title: 'Why Your API is Making Frontend Developers’ Lives Harder (And How to Fix It)',
          timeSlot: '11:20am - 11:45am',
          room: 'Emerald Hall',
          duration: '25m',
          timeFrame: '11am',
          type: 'session',
          speaker: 'Olamide Ilori',
          color: '#90EAF2',
        },
        {
          id: 'autonomous-apis-can-apis-self-heal-and-self-optimize-fri',
          title: 'Autonomous APIs: Can APIs Self-Heal and Self-Optimize?',
          timeSlot: '11:20am - 11:45am',
          room: 'Amber Hall',
          duration: '25m',
          timeFrame: '11am',
          type: 'session',
          speaker: 'Olakunle Dosunmu',
          color: '#ECC89D',
        },
        {
          id: 'building-an-ai-documentation-agent-for-your-api-using-rag-fri',
          title: 'Building an AI Documentation Agent for Your API using RAG',
          timeSlot: '11:45am - 12:30pm',
          room: 'Ruby Hall',
          duration: '45m',
          timeFrame: '11am',
          type: 'workshop',
          speaker: 'Favour Onuoha',
          color: '#E1EF9A',
        },
        {
          id: 'api-specifications-open-banking-specification-fri',
          title: 'API Specifications: Open Banking Specification',
          timeSlot: '11:45am - 12:30pm',
          room: 'Emerald Hall',
          duration: '45m',
          timeFrame: '11am',
          type: 'workshop',
          speaker: 'Oluwatimilehin Samuel Alapakristi',
          color: '#90EAF2',
        },
        {
          id: 'getting-your-openapi-spec-ready-for-code-generation-fri',
          title: 'Getting Your OpenAPI Spec Ready for Code Generation',
          timeSlot: '11:45am - 12:30pm',
          room: 'Amber Hall',
          duration: '45m',
          timeFrame: '11am',
          type: 'workshop',
          speaker: 'Funke Olasupo',
          color: '#ECC89D',
        },
        {
          id: 'general-lunch-fri',
          title: 'General Lunch',
          timeSlot: '12:30pm - 01:30pm',
          room: 'Ruby Hall',
          duration: '1hr ',
          timeFrame: '12pm',
          type: 'General Lunch',
          color: '#D9D9D9',
        },
        {
          id: 'async-api-slot-fri',
          title: 'An Intro to AsyncAPI Without The Technical Jargon',
          timeSlot: '01:30pm - 02:00pm',
          room: 'Amber Hall',
          duration: '30mins',
          timeFrame: '1pm',
          type: 'Async API',
          speaker: 'Azeez Elegbede & Thulisile Sibanda',
          color: '#99DED5',
        },
        {
          id: 'api-security-in-web3-protecting-decentralized-applications-from-common-threats-fri',
          title: 'API Security in Web3: Protecting Decentralized Applications from Common Threats',
          timeSlot: '01:30pm - 01:40pm',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '1pm',
          type: 'Lightning',
          speaker: 'Daniel Anomfueme',
          color: '#90EAF2',
        },
        {
          id: 'next-gen-api-as-a-service-ai-driven-delivery,-adaptive-documentation,-and-seamless-integration-fri',
          title:
            'Next-Gen API as a Service: AI-Driven Delivery, Adaptive Documentation, and Seamless Integration',
          timeSlot: '01:40pm - 02:05pm',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '1pm',
          type: 'session',
          speaker: 'Abimbola Bajomo',
          color: '#90EAF2',
        },
        {
          id: 'designing-seamless-api-experiences-integrating-product-design-with-api-innovation-fri',
          title:
            'Designing Seamless API Experiences: Integrating Product Design with API Innovation',
          timeSlot: '01:40pm - 02:05pm',
          room: 'Emerald Hall',
          duration: '25m',
          timeFrame: '1pm',
          type: 'session',
          speaker: 'Justice Anaba',
          color: '#ECC89D',
        },
          {
          id: 'async-api-slot-fri',
          title: 'From Ingredients to Output: The AsyncAPI Generator 101',
          timeSlot: '02:00pm - 02:30pm',
          room: 'Amber Hall',
          duration: '30mins',
          timeFrame: '2pm',
          type: 'Async API',
          speaker: 'Thulisile Sibanda',
          color: '#99DED5',
        },
        {
          id: 'monitoring-your-apis-like-a-superhero-with-the-kubernetes-prometheus-stack-fri',
          title: 'Monitoring your APIs like a SuperHero with the Kubernetes prometheus stack',
          timeSlot: '02:05pm - 02:50pm',
          room: 'Ruby Hall',
          duration: '45m',
          timeFrame: '2pm',
          type: 'workshop',
          speaker: 'Michael Mekuleyi',
          color: '#E1EF8B',
        },
        {
          id: 'server-side-rendering-with-dart-building-dynamic-web-applications-fri',
          title: 'Server-Side Rendering with Dart: Building Dynamic Web Applications',
          timeSlot: '02:05pm - 02:50pm',
          room: 'Emerald Hall',
          duration: '45m',
          timeFrame: '2pm',
          type: 'workshop',
          speaker: 'Samuel Abada',
          color: '#90EAF2',
        },
        {
          id: 'async-api-slot-fri',
          title: 'I Came to Design, I Ended Up Leading a Movement',
          timeSlot: '02:30pm - 3:00pm',
          room: 'Amber Hall',
          duration: '30mins',
          timeFrame: '2pm',
          type: 'Async API',
          speaker: 'Aishat Muibudeen',
          color: '#99DED5',
        },
        {
          id: 'ai-driven-hateoas-fri',
          title: 'AI-driven HATEOAS',
          timeSlot: '02:50pm - 03:15pm',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '2pm',
          type: 'session',
          speaker: 'Pratham Kumar',
          color: '#ECC89D',
        },
        {
          id: 'apis-don’t-speak-—-dashboards-do-fri',
          title: 'APIs Don’t Speak — Dashboards Do',
          timeSlot: '02:50pm - 03:15pm',
          room: 'Emerald Hall',
          duration: '25m',
          timeFrame: '2pm',
          type: 'session',
          speaker: 'Nwaamaka Iduwe',
          color: '#E1EF9A',
        },
        {
          id: 'async-api-slot-fri',
          title: 'Preventing API Drift',
          timeSlot: '03:00pm - 3:45pm',
          room: 'Amber Hall',
          duration: '30mins',
          timeFrame: '3pm',
          type: 'Async API',
          speaker: 'Azeez Elegbede',
          color: '#99DED5',
        },
        {
          id: 'from-vision-to-execution-building-apis-as-scalable-products-in-fintech-fri',
          title: 'From Vision to Execution: Building APIs as Scalable Products in Fintech',
          timeSlot: '03:15pm - 04:00pm',
          room: 'Ruby Hall',
          duration: '45m',
          timeFrame: '3pm',
          type: 'workshop',
          speaker: 'Solomon Olalemi',
          color: '#90EAF2',
        },
        {
          id: 'tested-and-trusted--building-testable-apis-and-testing-testable-apis.-fri',
          title: 'Tested and Trusted : Building Testable APIs and Testing Testable APIs.',
          timeSlot: '03:15pm - 04:00pm',
          room: 'Emerald Hall',
          duration: '45m',
          timeFrame: '3pm',
          type: 'workshop',
          speaker: 'Fehintoluwa Dahunsi',
          color: '#ECC89D',
        },
          {
          id: 'async-api-slot-fri',
          title: "Contributing to AsyncAPI from a Technical Writer's POV",
          timeSlot: '03:45pm - 4:30pm',
          room: 'Amber Hall',
          duration: '30mins',
          timeFrame: '3pm',
          type: 'Async API',
          speaker: 'Prince Onyeanuna & Ezinne Anne Emilia',
          color: '#99DED5',
        },
        {
          id: 'banking-without-banks-building-resilient-wallet-infrastructure-in-unstable-times-fri',
          title:
            'Banking Without Banks? Building Resilient Wallet Infrastructure in Unstable Times',
          timeSlot: '04:00pm - 04:25pm',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '4pm',
          type: 'session',
          speaker: 'Mustapha Rufai',
          color: '#E1EF9A',
        },
        {
          id: 'designing-developer-friendly-apis-a-frontend-engineer’s-wishlist-fri',
          title: 'Designing Developer-Friendly APIs: A Frontend Engineer’s Wishlist',
          timeSlot: '04:00pm - 04:25pm',
          room: 'Emerald Hall',
          duration: '25m',
          timeFrame: '4pm',
          type: 'session',
          speaker: 'Joshua Onyeuche',
          color: '#90EAF2',
        },
      ],
    },
    {
      dayNumber: 2,
      date: 'Sat 19 Jul',
      sessions: [
        {
          id: 'check-in-sat',
          title: 'Not Just in the Room, At the Table: Inspiring women to lead',
          timeSlot: '08:00am - 08:05am',
          room: 'Ruby Hall',
          duration: '5m',
          timeFrame: '8am',
          type: 'Women In API',
          speaker:'Atinuke Oluwabamikemi Kayode',
          color: '#D8CCFE',
        },
        {
          id: 'check-in-sat',
          title: 'Empowering Women in API: Navigating the Tech Ladder from Developers to Leaders',
          timeSlot: '08:05am - 08:50am',
          room: 'Ruby Hall',
          duration: '45m',
          timeFrame: '8am',
          panelist: 'Motunrayo Koyejo, Mfonobong Umondia, Olasupo Funke',
          host: 'Faith Mona Alumona',
          type: 'Women In API',
          color: '#D8CCFE',
        },
        {
          id: 'check-in-sat',
          title: 'Women In API - Q & A Session',
          timeSlot: '08:50am - 09:00am',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '8am',
          type: 'Women In API',
          color: '#D8CCFE',
        },
        {
          id: 'check-in-sat',
          title: 'Women In API - Group Pictures, Closing remarks',
          timeSlot: '09:00am - 09:10am',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '9am',
          type: 'Women In API',
          color: '#D8CCFE',
        },
        {
          id: 'check-in-sat',
          title: 'Networking Break',
          timeSlot: '09:10am - 09:30am',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '9am',
          type: 'Coffee Break',
          color: '#D9D9D9',
        },
        {
          id: "mehdi's-keynote-session-sat",
          title: "The API Mindset for Mass Innovation",
          timeSlot: '09:30am - 09:45am',
          room: 'Ruby Hall',
          duration: '15m',
          timeFrame: '9am',
          type: 'Keynote',
          speaker: 'Mehdi Medjaoui',
          color: '#ECC89D',
        },
        {
          id: 'devops-meets-apis-building,-governing,-&-scaling-api-first-architectures-for-enterprise-application-sat',
          title:
            'DevOps Meets APIs: Building, Governing, & Scaling API-First Architectures for Enterprise Application',
          timeSlot: '09:45am - 10:00am',
          room: 'Ruby Hall',
          duration: '15m',
          timeFrame: '9am',
          type: 'Keynote',
          speaker: 'Ademola Adelekan',
          color: '#ECC89D',
        },
        {
          id: 'caching-strategies-for-high-traffic-apis-sat',
          title: 'Caching Strategies for High-Traffic APIs',
          timeSlot: '10:00am - 10:10am',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '10am',
          type: 'Lightning',
          speaker: 'Nelson Isioma',
          color: '#90EAF2',
        },
        {
          id: 'embedded-insurance-in-5-minutes-sat',
          title: 'Embedded Insurance in 5 Minutes',
          timeSlot: '10:10am - 10:20am',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '10am',
          type: 'Lightning',
          speaker: 'Kimberly Samugana',
          color: '#90EAF2',
        },
        {
          id: 'embedded-insurance-in-5-minutes-sat',
          title: 'Mycover.ai: API Innovation in action',
          timeSlot: '10:20am - 10:30am',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '10am',
          type: 'Lightning',
          speaker: 'Omonigho Jimmy',
          color: '#90EAF2 ',
        },
        {
          id: 'redis-in-action-from-simple-cache-to-advanced-queues-and-streams-sat',
          title: 'Redis in Action: From Simple Cache to Advanced Queues and Streams',
          timeSlot: '10:30am - 10:55am',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '10am',
          type: 'session',
          speaker: 'Kenechukwu Ozordi',
          color: '#E1EF9A',
        },
        {
          id: 'from-chaos-to-clarity-building-api-integrations-that-don’t-burn-out-your-team-or-product-sat',
          title:
            'From Chaos to Clarity: Building API Integrations That Don’t Burn Out Your Team or Product',
          timeSlot: '10:30am - 10:55am',
          room: 'Emerald Hall',
          duration: '25m',
          timeFrame: '10am',
          type: 'session',
          speaker: 'Simi Oluwatomi',
          color: '#90EAF2',
        },
        {
          id: 'building-resilient-microservice-apis-engineering-for-high-stakes-environments-sat',
          title: 'Building Resilient Microservice APIs: Engineering for High-Stakes Environments',
          timeSlot: '10:30am - 10:55am',
          room: 'Amber Hall',
          duration: '25m',
          timeFrame: '10am',
          type: 'session',
          speaker: 'Ibiniyi Obikoya',
          color: '#ECC89D',
        },
        {
          id: 'morning-coffee/break-sat',
          title: 'Networking Break',
          timeSlot: '10:55am - 11:20am',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '10am',
          type: 'Coffee/Break',
          color: '#D9D9D9',
        },
        {
          id: 'detecting-the-undetectable-applying-merkle-trees-and-llms-to-software-monitoring-sat',
          title:
            'Detecting the Undetectable: Applying Merkle Trees and LLMs to Software Monitoring',
          timeSlot: '11:20am - 11:45am',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '11am',
          type: 'session',
          speaker: 'Anthony Alaribe',
          color: '#E1EF9A',
        },
        {
          id: 'detecting-threats-and-anomalies-in-api-traffic-with-ai-models.-sat',
          title: 'Detecting threats and anomalies in API traffic with AI models.',
          timeSlot: '11:20am - 11:45am',
          room: 'Emerald Hall',
          duration: '25m',
          timeFrame: '11am',
          type: 'session',
          speaker: 'Alexander Garuba',
          color: '#90EAF2',
        },
        {
          id: 'beyond-api-keys-advanced-strategies-for-securing-mobile-api-integrations-sat',
          title: 'Beyond API Keys: Advanced Strategies for Securing Mobile API Integrations',
          timeSlot: '11:20am - 11:45am',
          room: 'Amber Hall',
          duration: '25m',
          timeFrame: '11am',
          type: 'session',
          speaker: 'Atuoha Anthony',
          color: '#ECC89D',
        },
        {
          id: 'google-codelab-sat',
          title: 'How Machines See: Build a product image search backend with Visison API Product Search',
          timeSlot: '11:45am - 12:30pm',
          room: 'Ruby Hall',
          duration: '45m',
          timeFrame: '11am',
          type: 'workshop',
          speaker: 'Buchi Michelle Okonicha',
          color: '#E1EF9A',
        },
        {
          id: 'google-codelab-sat',
          title: 'Powering Payments with ALATPay: Tools, APIs, and SDKs for Engineers',
          timeSlot: '11:45am - 12:30pm',
          room: 'Emerald Hall',
          duration: '45m',
          timeFrame: '11am',
          type: 'workshop',
          speaker: 'Adejoke Haastrup',
          color: '#E1EF9A',
        },
        {
          id: 'leveraging-subgraph-apis-for-real-time-blockchain-data-sat',
          title: 'Leveraging Subgraph APIs for Real-Time Blockchain Data',
          timeSlot: '11:45am - 12:30pm',
          room: 'Amber Hall',
          duration: '45m',
          timeFrame: '11am',
          type: 'workshop',
          speaker: 'Emmanuel Odianosen',
          color: '#90EAF2',
        },
        {
          id: 'scaling-payroll-across-africa-sat',
          title: 'Scaling Payroll Across Africa',
          timeSlot: '12:30pm - 12:55pm',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '12pm',
          type: 'session',
          speaker: 'Favour Oriabure',
          color: '#E1EF9A',
        },
        {
          id: 'the-art-and-science-of-lovable-api-documentation-lessons-from-the-monnify-revamp-sat',
          title:
            'The Art and Science of Lovable API Documentation: Lessons from the Monnify Revamp',
          timeSlot: '12:30pm - 12:55pm',
          room: 'Emerald Hall',
          duration: '25m',
          timeFrame: '12pm',
          type: 'session',
          speaker: 'Auwal MS',
          color: '#90EAF2',
        },
        {
          id: 'api-driven-innovation-mycover.ai’s-blueprint-for-modernizing-insurance-ecosystems-sat',
          title:
            'API-Driven Innovation: MyCover.ai’s Blueprint for Modernizing Insurance Ecosystems',
          timeSlot: '12:30pm - 12:55pm',
          room: 'Amber Hall',
          duration: '25m',
          timeFrame: '12pm',
          type: 'session',
          speaker: 'Oluwaseun Dabiri',
          color: '#ECC89D',
        },
        {
          id: 'general-lunch-sat',
          title: 'General Lunch',
          timeSlot: '12:55pm - 01:55pm',
          room: 'Ruby Hall',
          duration: '1hr ',
          timeFrame: '1pm',
          type: 'General Lunch',
          color: '#D9D9D9',
        },
        {
          id: 'interswitch-15mins-session-sat',
          title: 'CloudPlexo',
          timeSlot: '01:55pm - 02:00pm',
          room: 'Ruby Hall',
          duration: '5m',
          timeFrame: '2pm',
          type: 'Lightning',
          speaker: 'David Ekefre',
          color: '#90EAF2',
        },
        {
          id: 'interswitch-15mins-session-sat',
          title: 'A Code-First Framework for building API-Driven Features',
          timeSlot: '02:00pm - 02:05pm',
          room: 'Ruby Hall',
          duration: '5m',
          timeFrame: '2pm',
          type: 'session',
          speaker: 'Ifedayo Sanni',
          color: '#90EAF2',
        },
        {
          id: 'how-we-monitor-and-maintain-over-40-third-party-integrations-at-involve.me-sat',
          title: 'How we monitor and maintain over 40 third party integrations at involve.me',
          timeSlot: '02:05pm - 02:15pm',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '2pm',
          type: 'Lightning',
          speaker: 'Paul Adams',
          color: '#90EAF2',
        },       
         {
          id: 'interswitch-15mins-session-sat',
          title: 'Interswitch API Demo',
          timeSlot: '02:15pm - 02:25pm',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '2pm',
          type: 'Lightning',
          speaker: 'Oluwatayo Farotimi',
          color: '#90EAF2',
        },
        {
          id: 'panel-sessionnnnnnnn-!!!!-sat', 
          title: 'The Future of APIs in an AI-First World - Will LLMs change how we design, expose, and secure APIs?',
          timeSlot: '02:25pm - 02:55pm',
          room: 'Ruby Hall',
          duration: '30m',
          timeFrame: '2pm',
          type: 'Panel session',
          panelist: 'Robert (Thas) John, Luc Okalobe, Awonuga Sherif, Taiwo Coker',
          host: 'Claret Ibeawuchi',
          color: '#E1EF9A',
        },
        {
          id: 'interswitch-15mins-session-sat',
          title: 'The Future of payments',
          timeSlot: '02:55pm - 03:05pm',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '2pm',
          type: 'Lightning',
          speaker: 'Adejoke Haastrup',
          color: '#90EAF2',
        },
        {
          id: 'interswitch-15mins-session-sat',
          title: 'Globarman API Demo By David',
          timeSlot: '03:05pm - 03:10pm',
          room: 'Ruby Hall',
          duration: '5m',
          timeFrame: '3pm',
          type: 'Lightning',
          speaker: '',
          color: '#90EAF2',
        },
        {
          id: 'wema-bank-session-sat',
          title: "Announcing the Winners Postman's Notebook Challenge",
          timeSlot: '03:05pm - 3:10pm',
          room: 'Ruby Hall',
          duration: '5m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Gbadebo Bello',
          color: '#90EAF2',
        },
        {
          id: 'shaping-the-future-of-semiconductor-manufacturing-with-genai-sat',
          title: 'How to design API Documentation that Technical & Non-technical Audience love',
          timeSlot: '03:15pm - 3:40pm',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Mfonobong Umondia',
          color: '#ECC89D',
        },
        {
          id: 'how-to-design-api-documentation-that-technical-&-non-technical-audience-love-sat',
          title: 'Microservices Architecture 101: Principles and Best Practices',
          timeSlot: '03:15pm - 3:40pm',
          room: 'Emerald Hall',
          duration: '25m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Glory Olamigoke',
          color: '#E1EF9A',
        },
        {
          id: 'how-to-design-api-documentation-that-technical-&-non-technical-audience-love-sat',
          title: 'Mastering APIs as a Product Manager - Calling , Documenting and Testing APIs',
          timeSlot: '03:15pm - 3:40pm',
          room: 'Amber Hall',
          duration: '25m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Aminat Fowoke Balogun',
          color: '#E1EF9A',
        },
        {
          id: 'refactoring-legacy-apis-with-domain-driven-architecture-sat',
          title: 'Refactoring Legacy APIs with Domain-Driven Architecture',
          timeSlot: '03:40pm - 04:05pm',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Ijeoma Eti',
          color: '#ECC89D',
        },
        {
          id: 'microservices-architecture-101-principles-and-best-practices-sat',
          title: 'API-first DevOps: Automating API deployments for speed and scale',
          timeSlot: '03:40pm - 04:05pm',
          room: 'Emerald Hall',
          duration: '25m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Daniel Adeboye',
          color: '#E1EF9A',
        },
        {
          id: 'dart-on-the-server-unlocking-full-stack-potential-sat',
          title: 'Dart on the Server: Unlocking Full-Stack Potential',
          timeSlot: '03:40pm - 04:05pm',
          room: 'Amber Hall',
          duration: '25m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Jamiu Okanlawon',
          color: '#90EAF2',
        },
        {
          id: 'securing-the-fort-api-gateway-architectures,-and-why-they-matter-sat',
          title: 'Securing The Fort: API Gateway Architectures, and why they matter',
          timeSlot: '04:05pm - 04:30pm',
          room: 'Ruby Hall',
          duration: '25m',
          timeFrame: '4pm',
          type: 'session',
          speaker: 'Chukwuemeka Chukwurah',
          color: '#ECC89D',
        },
        {
          id: 'api-first-devops-automating-api-deployments-for-speed-and-scale-sat',
          title: `Don't Ask me Coffee - I'm a Teapot!`,
          timeSlot: '04:05pm - 04:30pm',
          room: 'Emerald Hall',
          duration: '25m',
          timeFrame: '4pm',
          type: 'session',
          speaker: 'Olayinka Atobiloye',
          color: '#E1EF9A',
        },
        {
          id: 'dart-on-the-server-unlocking-full-stack-potential-sat',
          title: 'API Design from a Frontend Perspective: What We Wish Backend Engineers Knew',
          timeSlot: '04:05pm - 04:30pm',
          room: 'Amber Hall',
          duration: '25m',
          timeFrame: '4pm',
          type: 'session',
          speaker: 'Ayantunji Timilehin',
          color: '#90EAF2',
        },
          {
          id: 'interswitch-15mins-session-sat',
          title: 'Closing By APIConf',
          timeSlot: '04:30pm - 05:00pm',
          room: 'Ruby Hall',
          duration: '10m',
          timeFrame: '4pm',
          type: 'Closing event',
          speaker: '',
          color: '#D9D9D9',
        },
      ],
    },
  ],
};
