export const scheduleData = {
  title: 'Your Day at a Glance',
  days: [
    {
      dayNumber: 1,
      date: 'Fri 24 Jul',
      sessions: [
        {
          id: 'opening-remark-welcome-networking-fri',
          title: 'Opening remark, welcome, Networking',
          timeSlot: '09:00am - 10:00am',
          room: 'Emerald Hall',
          duration: '1hr',
          timeFrame: '9am',
          type: 'Welcome',
          color: '#D9D9D9',
        },
        {
          id: 'monitoring-apis-with-opentelemetry-fri',
          title: 'Monitoring APIs with OpenTelemetry',
          timeSlot: '10:00am - 10:45am',
          room: 'Ruby Hall',
          duration: '45m',
          timeFrame: '10am',
          type: 'workshop',
          speaker: 'Ayooluwa Isaiah',
          color: '#F0E6FF',
        },
        {
          id: 'the-lazy-way-to-keep-your-api-docs-in-sync-fri',
          title: 'The lazy way to keep your API Docs in sync',
          timeSlot: '10:00am - 10:45am',
          room: 'Emerald Hall',
          duration: '45m',
          timeFrame: '10am',
          type: 'workshop',
          speaker: 'Prince Onyeanuna',
          color: '#F0E6FF',
        },
        {
          id: 'type-safe-apis-with-hono-and-zod-fri',
          title: 'Type-Safe APIs with Hono and Zod: Fast, Lightweight, and Bulletproof',
          timeSlot: '10:00am - 10:45am',
          room: 'Amber Hall',
          duration: '45m',
          timeFrame: '10am',
          type: 'workshop',
          speaker: 'Chinedu Otutu',
          color: '#F0E6FF',
        },
        {
          id: 'sponsor-workshop-1-fri',
          title: 'Sponsor Workshop 1',
          timeSlot: '11:00am - 11:45am',
          room: 'Ruby Hall',
          duration: '45m',
          timeFrame: '11am',
          type: 'workshop',
          speaker: 'TBH',
          color: '#F0E6FF',
        },
        {
          id: 'your-api-docs-are-breaking-ai-fri',
          title: 'Your API Docs Are Breaking AI',
          timeSlot: '11:00am - 11:45am',
          room: 'Emerald Hall',
          duration: '45m',
          timeFrame: '11am',
          type: 'workshop',
          speaker: 'Funke Olasupo',
          color: '#F0E6FF',
        },
        {
          id: 'rethinking-caching-agentic-systems-fri',
          title:
            'Rethinking Caching: Building APIs For The Unpredictable Traffic from Agentic Systems',
          timeSlot: '11:00am - 11:45am',
          room: 'Amber Hall',
          duration: '45m',
          timeFrame: '11am',
          type: 'workshop',
          speaker: 'Alayesanmi Femi',
          color: '#F0E6FF',
        },
        {
          id: 'hacking-apis-in-the-wild-fri',
          title:
            'Hacking APIs in the Wild: Finding, Exploiting & Reporting Modern API Vulnerabilities',
          timeSlot: '12:00pm - 12:45pm',
          room: 'Ruby Hall',
          duration: '45m',
          timeFrame: '12pm',
          type: 'workshop',
          speaker: 'Tes Sal',
          color: '#F0E6FF',
        },
        {
          id: 'sponsor-workshop-2-fri',
          title: 'Sponsor Workshop 2',
          timeSlot: '12:00pm - 12:45pm',
          room: 'Emerald Hall',
          duration: '45m',
          timeFrame: '12pm',
          type: 'workshop',
          speaker: 'TBH',
          color: '#F0E6FF',
        },
        {
          id: 'building-your-first-ai-agent-with-genkit-fri',
          title: 'Building Your First AI Agent with Genkit',
          timeSlot: '12:00pm - 12:45pm',
          room: 'Amber Hall',
          duration: '45m',
          timeFrame: '12pm',
          type: 'workshop',
          speaker: 'Jamiu Okanlawon',
          color: '#F0E6FF',
        },
        {
          id: 'lunch-fri',
          title: 'Lunch',
          timeSlot: '01:00pm - 02:00pm',
          room: 'All Halls',
          duration: '1hr',
          timeFrame: '1pm',
          type: 'session',
          color: '#D9D9D9',
        },
        {
          id: 'from-monolith-to-microservices-fri',
          title: 'From Monolith to Microservices: Designing Resilient, Observable APIs with Node.js',
          timeSlot: '02:00pm - 02:45pm',
          room: 'Ruby Hall',
          duration: '45m',
          timeFrame: '2pm',
          type: 'workshop',
          speaker: 'Usman Soliu',
          color: '#F0E6FF',
        },
        {
          id: 'building-secure-scalable-api-infrastructure-azure-fri',
          title:
            'Building Robust, Secure, and Scalable API Infrastructure with Microsoft Azure Services',
          timeSlot: '02:00pm - 02:45pm',
          room: 'Emerald Hall',
          duration: '45m',
          timeFrame: '2pm',
          type: 'workshop',
          speaker: 'Timothy Ogunwemimo',
          color: '#F0E6FF',
        },
        {
          id: 'from-rest-to-mcp-fastmcp-fri',
          title: 'From REST to MCP: Making Your Backend AI-Ready with FastMCP',
          timeSlot: '03:00pm - 03:45pm',
          room: 'Ruby Hall',
          duration: '45m',
          timeFrame: '3pm',
          type: 'workshop',
          speaker: 'Abdulqudus Abubakre',
          color: '#F0E6FF',
        },
        {
          id: 'from-scattered-docs-to-instant-answers-langchain-fri',
          title:
            'From Scattered Docs to Instant Answers: How We Built an Internal Knowledge Graph with LangChain',
          timeSlot: '03:00pm - 03:45pm',
          room: 'Emerald Hall',
          duration: '45m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Kelechi Oliver Azorji',
          color: '#E1EF8B',
        },
        {
          id: 'closing-photos-fri',
          title: 'Closing, Photos',
          timeSlot: '03:45pm - 04:00pm',
          room: 'All Halls',
          duration: '15m',
          timeFrame: '3pm',
          type: 'session',
          color: '#D9D9D9',
        },
      ],
    },
    {
      dayNumber: 2,
      date: 'Sat 25 Jul',
      sessions: [
        {
          id: 'welcome-address-and-opening-sat',
          title: 'Welcome Address and Opening',
          timeSlot: '09:00am - 10:00am',
          room: 'Main Stage',
          duration: '1hr',
          timeFrame: '9am',
          type: 'Welcome',
          color: '#D9D9D9',
        },
        {
          id: 'from-prompts-to-autonomous-systems-sat',
          title:
            'From Prompts to Autonomous Systems: Architecting Production-Ready AI Agents on Google Cloud',
          timeSlot: '10:00am - 10:20am',
          room: 'Emerald Hall',
          duration: '20m',
          timeFrame: '10am',
          type: 'Lightning',
          speaker: 'Peterson Nwoko',
          color: '#90EAF2',
        },
        {
          id: 'announcement-1020-sat',
          title: 'Announcement',
          timeSlot: '10:20am - 10:30am',
          room: 'Main Stage',
          duration: '10m',
          timeFrame: '10am',
          type: 'Announcement',
          color: '#D9D9D9',
        },
        {
          id: 'where-will-ai-converge-sat',
          title: 'Where will AI Converge: No intelligence without Energy',
          timeSlot: '10:30am - 10:45am',
          room: 'Ruby Hall',
          duration: '15m',
          timeFrame: '10am',
          type: 'Lightning',
          speaker: 'Ibukun Adedeji',
          color: '#90EAF2',
        },
        {
          id: 'the-assumptions-that-break-apis-in-production-sat',
          title: 'The Assumptions That Break APIs in Production',
          timeSlot: '10:30am - 10:45am',
          room: 'Emerald Hall',
          duration: '15m',
          timeFrame: '10am',
          type: 'Lightning',
          speaker: 'Ayomide Ariyo',
          color: '#90EAF2',
        },
        {
          id: 'announcement-1045-sat',
          title: 'Announcement',
          timeSlot: '10:45am - 10:50am',
          room: 'Main Stage',
          duration: '5m',
          timeFrame: '10am',
          type: 'Announcement',
          color: '#D9D9D9',
        },
        {
          id: 'gsma-keynote-sat',
          title: 'GSMA Keynote',
          timeSlot: '10:50am - 11:05am',
          room: 'Main Stage',
          duration: '15m',
          timeFrame: '10am',
          type: 'session',
          color: '#D9D9D9',
        },
        {
          id: 'gsma-panel-session-sat',
          title: 'GSMA panel session',
          timeSlot: '11:05am - 11:25am',
          room: 'Main Stage',
          duration: '20m',
          timeFrame: '11am',
          type: 'Panel session',
          color: '#D8CCFE',
        },
        {
          id: 'ai-agents-need-guardrails-sat',
          title: 'AI Agents Need Guardrails: Securing APIs in the Age of Autonomous Systems',
          timeSlot: '11:25am - 11:55am',
          room: 'Ruby Hall',
          duration: '30m',
          timeFrame: '11am',
          type: 'session',
          speaker: 'Obi Uchenna David',
          color: '#E1EF8B',
        },
        {
          id: 'governance-without-the-bureaucracy-sat',
          title:
            'Governance Without the Bureaucracy: How to Enforce API Standards Without Slowing Down Your Team',
          timeSlot: '11:25am - 11:55am',
          room: 'Emerald Hall',
          duration: '30m',
          timeFrame: '11am',
          type: 'session',
          speaker: 'Amarachi Iheanacho',
          color: '#E1EF8B',
        },
        {
          id: 'software-is-going-headless-sat',
          title: 'Software Is Going Headless: What the API Becomes When Agents Run Everything',
          timeSlot: '11:25am - 11:55am',
          room: 'Amber Hall',
          duration: '30m',
          timeFrame: '11am',
          type: 'session',
          speaker: 'Joel Olawanle',
          color: '#E1EF8B',
        },
        {
          id: 'designing-apis-as-products-sat',
          title: 'Designing APIs as Products: How Product Thinking Improves Developer Experience',
          timeSlot: '12:05pm - 12:35pm',
          room: 'Ruby Hall',
          duration: '30m',
          timeFrame: '12pm',
          type: 'session',
          speaker: 'Cindy Shontan',
          color: '#E1EF8B',
        },
        {
          id: 'ai-can-write-code-sat',
          title: 'AI Can Write Code. But It Doesn’t Know Your System',
          timeSlot: '12:05pm - 12:35pm',
          room: 'Emerald Hall',
          duration: '30m',
          timeFrame: '12pm',
          type: 'session',
          speaker: 'Chigozie Madubuko',
          color: '#E1EF8B',
        },
        {
          id: 'building-crypto-payment-apis-in-africa-sat',
          title:
            'Building Crypto Payment APIs in Africa: Stablecoins, On-Ramps & the Regulatory Tightrope',
          timeSlot: '12:05pm - 12:35pm',
          room: 'Amber Hall',
          duration: '30m',
          timeFrame: '12pm',
          type: 'session',
          speaker: 'Progress Ochuko Eyaadah (Koxy)',
          color: '#E1EF8B',
        },
        {
          id: 'ice-breaker-sat',
          title: 'Ice breaker',
          timeSlot: '12:35pm - 12:45pm',
          room: 'Main Stage',
          duration: '10m',
          timeFrame: '12pm',
          type: 'session',
          color: '#D9D9D9',
        },
        {
          id: 'main-stage-2-sat',
          title: 'Main stage 2',
          timeSlot: '12:45pm - 01:00pm',
          room: 'Main Stage',
          duration: '15m',
          timeFrame: '12pm',
          type: 'session',
          color: '#D9D9D9',
        },
        {
          id: 'lunch-sat',
          title: 'Lunch',
          timeSlot: '01:00pm - 02:00pm',
          room: 'All Halls',
          duration: '1hr',
          timeFrame: '1pm',
          type: 'session',
          color: '#D9D9D9',
        },
        {
          id: 'hackathon-announcement-sat',
          title: 'Hackathon announcement',
          timeSlot: '02:00pm - 02:15pm',
          room: 'Main Stage',
          duration: '15m',
          timeFrame: '2pm',
          type: 'Announcement',
          color: '#D9D9D9',
        },
        {
          id: 'main-stage-3-sat',
          title: 'Main stage 3',
          timeSlot: '02:15pm - 02:30pm',
          room: 'Main Stage',
          duration: '15m',
          timeFrame: '2pm',
          type: 'session',
          color: '#D9D9D9',
        },
        {
          id: 'building-compliant-fintech-apis-sat',
          title: 'Building Compliant Fintech APIs for African Corridors',
          timeSlot: '02:30pm - 03:00pm',
          room: 'Ruby Hall',
          duration: '30m',
          timeFrame: '2pm',
          type: 'session',
          speaker: 'Oluwatoni Akinmolayan',
          color: '#E1EF8B',
        },
        {
          id: 'panel-session-sat',
          title: 'Panel Session',
          timeSlot: '02:30pm - 03:00pm',
          room: 'Emerald Hall',
          duration: '30m',
          timeFrame: '2pm',
          type: 'Panel session',
          color: '#D8CCFE',
        },
        {
          id: 'when-payments-fail-sat',
          title: 'When Payments Fail: Designing Resilient APIs for Fintech Systems',
          timeSlot: '02:30pm - 03:00pm',
          room: 'Amber Hall',
          duration: '30m',
          timeFrame: '2pm',
          type: 'session',
          speaker: 'Motunrayo Koyejo',
          color: '#E1EF8B',
        },
        {
          id: 'what-api-designers-can-learn-from-kubernetes-sat',
          title: 'What API Designers Can Learn from the Kubernetes API',
          timeSlot: '03:10pm - 03:40pm',
          room: 'Ruby Hall',
          duration: '30m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Somtochi Onyekwere',
          color: '#E1EF8B',
        },
        {
          id: 'improving-api-adoption-through-dx-sat',
          title: 'Improving API Adoption Through Developer Experience, Not Just Design',
          timeSlot: '03:10pm - 03:40pm',
          room: 'Emerald Hall',
          duration: '30m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Onyedikachi Hope Amaechi-Okorie',
          color: '#E1EF8B',
        },
        {
          id: 'when-your-api-is-slow-its-probably-sql-sat',
          title: 'When Your API Is Slow, It’s Probably SQL: Performance Tuning for Production APIs',
          timeSlot: '03:10pm - 03:40pm',
          room: 'Amber Hall',
          duration: '30m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Jamiu Adam',
          color: '#E1EF8B',
        },
        {
          id: 'the-apis-you-dont-control-sat',
          title:
            'The APIs You Don’t Control: Building on NIBSS, CBN & Payment Rails Without Losing Your Mind',
          timeSlot: '03:50pm - 04:20pm',
          room: 'Ruby Hall',
          duration: '30m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Ifeanyi Echereobia',
          color: '#E1EF8B',
        },
        {
          id: 'designing-better-developer-experience-for-web3-apis-sat',
          title: 'Designing Better Developer Experience for Web3 APIs',
          timeSlot: '03:50pm - 04:20pm',
          room: 'Emerald Hall',
          duration: '30m',
          timeFrame: '3pm',
          type: 'session',
          speaker: 'Nasihudeen Jimoh',
          color: '#E1EF8B',
        },
        {
          id: 'closing-sat',
          title: 'Closing Remarks, Networking, Photos',
          timeSlot: '04:20pm - 05:00pm',
          room: 'Main Stage',
          duration: '40m',
          timeFrame: '4pm',
          type: 'session',
          color: '#D9D9D9',
        },
      ],
    },
  ],
};
