import { useRef } from "react";
import rightImage from "../../assets/why-attend/why-attend-img.svg";
import { useIsVisible } from "../../hooks";
import { motion } from "framer-motion";

const WhyAttend = () => {
  const eventDetailsRef = useRef(null);
  const whyAttendRef = useRef(null);
  const whyAttendDescRef = useRef(null);
  const imgRef = useRef(null);
  const isEventDetailsVisible = useIsVisible(eventDetailsRef);
  const isWhyAttendVisible = useIsVisible(whyAttendRef);
  const isWhyAttendDescVisible = useIsVisible(whyAttendDescRef);
  const isImgVisible = useIsVisible(imgRef);

  return (
    <div className="bg-white px-8 sm:px-20 2xl:px-32 py-10 lg:py-32 flex flex-col md:flex-row items-center gap-16 sm:gap-x-20">
      <div className="flex-1 space-y-8">
        <motion.span
          ref={eventDetailsRef}
          initial={{ y: 32 }}
          animate={{ y: isEventDetailsVisible ? 0 : 32 }}
          transition={{
            duration: 1,
            ease: [0, 0, 0.25, 1],
          }}
          className="rounded-2xl border border-[#F7E7D4] px-3 py-1 text-[#6E6E6E] drop-shadow-2xl shadow-sm text-xs lg:text-lg font-bold"
        >
          Event Details
        </motion.span>
        <motion.h3
          ref={whyAttendRef}
          initial={{ y: 32 }}
          animate={{ y: isWhyAttendVisible ? 0 : 32 }}
          transition={{
            duration: 1,
            ease: [0, 0, 0.25, 1],
          }}
          className="font-bold text-3xl lg:text-5xl"
        >
          Why Attend?
        </motion.h3>
        <motion.p
          ref={whyAttendDescRef}
          initial={{ y: 32 }}
          animate={{ y: isWhyAttendDescVisible ? 0 : 32 }}
          transition={{
            duration: 1,
            ease: [0, 0, 0.25, 1],
          }}
          className="max-w-[600px]"
        >
          Some body of text to accompany visually solid idea per section. This
          text if fully generated by NOT an LLM and serves only the purpose of
          content. We need Content. Content is not just content. It is voice, it
          is king.
        </motion.p>
      </div>

      <div className="flex-1">
        <motion.img
          ref={imgRef}
          initial={{ y: 32 }}
          animate={{ y: isImgVisible ? 0 : 40 }}
          transition={{
            duration: 1,
            ease: [0, 0, 0.25, 1],
            delay: 0.2,
          }}
          src={rightImage}
          alt="why attend"
          className="rounded-[40px]"
        />
      </div>
    </div>
  );
};

export default WhyAttend;
