export default function PreFooterCta() {
  return (
    <section className="px-6 py-20 md:p-32">
      <div className="flex flex-col gap-x-16 gap-y-8 md:flex-row">
        <div className="flex-1 md:flex-[49_49_0%]">
          <div className="mb-8 h-[31rem] w-full rounded-[2rem] bg-[#D9D9D9]"></div>
          <figcaption>
            Some body of text to accompany visually solid idea per section. This text if fully
            generated by NOT an LLM and serves only the purpose of content. We need Content. Content
            is not just content. It is voice, it is king.
          </figcaption>
        </div>
        <div className="flex-1 md:flex-[39_39_0%]">
          <div className="mb-8 h-[31rem] w-full rounded-[2rem] bg-[#D9D9D9]"></div>
          <figcaption>Some body of text to accompany visually solid idea per section.</figcaption>
        </div>
      </div>
      <div className="mt-20 text-[#1F1F1F] md:mt-32">
        <span className="text-4xl font-bold md:text-5xl">Sponsor APIConf Lagos 2025</span>
        <p className="mb-12 mt-4 max-w-[29.3125rem] text-2xl font-medium">
          Learn more details to sponsor API Conference
        </p>
        <div className="flex flex-col gap-x-8 gap-y-12 md:flex-row">
          <a
            href="https://drive.google.com/file/d/1TYEN5HVH8_7ofGNpq2FoVniPskh6wXXe/view"
            rel="noopener noreferrer"
            target="_blank"
            className="flex w-full cursor-pointer items-center justify-center gap-2 rounded-[20rem] bg-[#2F20BF] p-6 sm:px-4 sm:py-8 md:w-fit md:px-16 lg:py-8"
          >
            <span className="text-center text-2xl font-bold text-white">View Sponsorship Deck</span>
          </a>
          <a
            href="https://docs.google.com/forms/d/e/1FAIpQLSeX_vB-R7Dw5wlmnz0jgpD8b14bsB0f6cbLhoHRYnFMxaNmLA/viewform"
            rel="noopener noreferrer"
            target="_blank"
            className="flex w-full cursor-pointer items-center justify-center gap-2 rounded-[20rem] bg-[#90EAF2] p-6 sm:px-4 sm:py-8 md:w-fit md:px-16 lg:py-8"
          >
            <span className="text-center text-2xl font-bold text-[#000]">Contact Us</span>
          </a>
        </div>
      </div>
    </section>
  );
}
