export default function PreFooterCta() {
  return (
    <section className="px-6 pb-20 md:px-32 md:pb-32">
      {/* <div className="pt-20 md:pt-32 flex flex-col gap-x-16 gap-y-8 md:flex-row">
        <div className="flex-1 md:flex-[49_49_0%]">
          <div className="mb-8 h-[31rem] w-full rounded-[2rem] bg-[#D9D9D9]"></div>
          <figcaption>
            Some body of text to accompany visually solid idea per section. This text if fully
            generated by NOT an LLM and serves only the purpose of content. We need Content. Content
            is not just content. It is voice, it is king.
          </figcaption>
        </div>
        <div className="flex-1 md:flex-[39_39_0%]">
          <div className="mb-8 h-[31rem] w-full rounded-[2rem] bg-[#D9D9D9]"></div>
          <figcaption>Some body of text to accompany visually solid idea per section.</figcaption>
        </div>
      </div> */}
      <div className="mt-20 text-[#1F1F1F] md:mt-32">
        <span className="text-4xl font-bold md:text-5xl">Sponsor APIConf Lagos 2026</span>
        <p className="mb-12 mt-4 max-w-[37.5rem] text-pretty text-2xl font-medium">
          Get access to an engaged audience and give your brand visibility! Partner with the leading
          API Conference in Africa
        </p>
        <div className="flex flex-col gap-x-8 gap-y-12 md:flex-row">
          <a
            href="https://drive.google.com/file/d/1i5eUM2ZHzFrKOaQ1TFo9snj06I6N8Av3/view"
            rel="noopener noreferrer"
            target="_blank"
            className="flex w-full cursor-pointer items-center justify-center gap-2 rounded-[20rem] bg-[#2F20BF] p-6 sm:px-4 sm:py-8 md:w-fit md:px-16 lg:py-8"
          >
            <span className="text-center text-2xl font-bold text-white">View Sponsorship Deck</span>
          </a>
          <a
            href="https://docs.google.com/forms/d/e/1FAIpQLSeX_vB-R7Dw5wlmnz0jgpD8b14bsB0f6cbLhoHRYnFMxaNmLA/viewform"
            rel="noopener noreferrer"
            target="_blank"
            className="flex w-full cursor-pointer items-center justify-center gap-2 rounded-[20rem] bg-[#90EAF2] p-6 sm:px-4 sm:py-8 md:w-fit md:px-16 lg:py-8"
          >
            <span className="text-center text-2xl font-bold text-[#000]">Contact Us</span>
          </a>
        </div>
      </div>
    </section>
  );
}
