export default function SponsorOpportunities() {
  return (
    <>
      <section className="my-20 px-6 md:p-32">
        <h2 className="mb-6 text-4xl font-bold text-[#000] md:text-[4rem]">
          Sponsor Opportunities
        </h2>
        <p className="max-w-[43.75rem] text-lg text-[#6E6E6E]">
          Some body of text to accompany visually solid idea per section. This text if fully
          generated by NOT an LLM and serves only the purpose of content. We need Content. Content
          is not just content. It is voice, it is king.
        </p>
      </section>
      <div className="w-full bg-[#000] px-6 py-16 md:py-32">
        <div className="w-full md:mx-auto md:max-w-[60%]">
          <p className="mb-4 text-center text-4xl font-bold text-[#F1F1F1] md:text-5xl">
            Together, we can shape the future of APIs in Africa, foster collaboration, and support
            the growth of a thriving API ecosystem.
          </p>
          <p className="mx-auto mb-12 max-w-[29.3125rem] text-center text-2xl font-medium text-[#F1F1F1]">
            Learn more details to sponsor API Conference
          </p>
          <div className="flex w-full flex-col gap-x-8 gap-y-12 md:mx-auto md:w-fit md:flex-row">
            <a
              href="https://drive.google.com/file/d/1TYEN5HVH8_7ofGNpq2FoVniPskh6wXXe/view"
              rel="noopener noreferrer"
              target="_blank"
              className="flex w-full cursor-pointer items-center justify-center gap-2 rounded-[20rem] bg-[#E1EF9A] p-6 sm:px-4 sm:py-8 md:w-fit md:px-16 lg:py-8"
            >
              <span className="text-2xl font-bold text-[#1F1F1F]">View Sponsorship Deck</span>
            </a>
            <a
              href="https://drive.google.com/file/d/1TYEN5HVH8_7ofGNpq2FoVniPskh6wXXe/view"
              rel="noopener noreferrer"
              target="_blank"
              className="flex w-full cursor-pointer items-center justify-center gap-2 rounded-[20rem] bg-[#1F1F1F] p-6 sm:px-4 sm:py-8 md:w-fit md:px-16 lg:py-8"
            >
              <span className="text-2xl font-bold text-white">Contact Us</span>
            </a>
          </div>
        </div>
      </div>
    </>
  );
}
