import SpacesCarousel from '@/components/Talks/spaces/spaces-carousel';

export default function SponsorExperience() {
  const slides = [
    {
      id: 1,
      image: '/events/event-1.jpg',
      alt: `Slide 1`,
    },
    {
      id: 2,
      image: '/events/event-2.jpg',
      alt: `Slide 2`,
    },
    {
      id: 3,
      image: '/events/event-3.jpg',
      alt: `Slide 3`,
    },
    {
      id: 4,
      image: '/events/event-4.jpg',
      alt: `Slide 4`,
    },
    {
      id: 5,
      image: '/events/event-5.jpg',
      alt: `Slide 5`,
    },
    {
      id: 6,
      image: '/events/event-6.jpg',
      alt: `Slide 6`,
    },
    {
      id: 7,
      image: '/events/event-7.jpg',
      alt: `Slide 7`,
    },
    {
      id: 8,
      image: '/events/event-8.jpg',
      alt: `Slide 8`,
    },
    {
      id: 9,
      image: '/events/event-9.jpg',
      alt: `Slide 9`,
    },
    {
      id: 10,
      image: '/events/event-10.jpg',
      alt: `Slide 10`,
    },
  ];

  return (
    <>
      <section className="bg-white px-8 py-20 text-[#000] md:p-32">
        <h2 className="mb-6 text-4xl font-bold md:text-[4rem]">Sponsor Experience</h2>
        <p className="mb-16 max-w-[37.1875rem] text-lg text-[#6E6E6E]">
          Some body of text to accompany visually solid idea per section. This text if fully
          generated by NOT an LLM and serves only the purpose of content. We need Content. Content
          is not just content. It is voice, it is king.
        </p>
        <div className="flex flex-col justify-between gap-x-8 gap-y-10 md:flex-row">
          <div className="md:max-w-[30%] 2xl:max-w-[25rem]">
            <span className="mb-4 text-4xl font-bold text-[#1F1F1F] md:text-5xl">Turnkey</span>
            <p className="text-lg text-[#6E6E6E]">
              You bring your brand vision, we’ll do the heavy lifting. With the help of our
              experiential design agency, we’ll bring your physical and digital presence to life.
            </p>
          </div>
          <div className="md:max-w-[30%] 2xl:max-w-[25rem]">
            <span className="mb-4 text-4xl font-bold text-[#1F1F1F] md:text-5xl">Bespoke</span>
            <p className="text-lg text-[#6E6E6E]">
              We understand that no two sponsors are alike. We’ll work with you to customize your
              sponsorship so that you can get in front of the right people at the right time.
            </p>
          </div>
          <div className="md:max-w-[30%] 2xl:max-w-[25rem]">
            <span className="mb-4 text-4xl font-bold text-[#1F1F1F] md:text-5xl">
              Beyond the booth
            </span>
            <p className="text-lg text-[#6E6E6E]">
              Let your dollars go further with a sponsorship that fosters high-quality conversations
              that drive impact––from surprise and delight add-ons to curated opportunities for
              connection.
            </p>
          </div>
        </div>
      </section>
      <div className="py-8 pl-8 md:pb-32 md:pl-32 2xl:pt-32">
        <div className="flex w-full gap-16">
          <SpacesCarousel>
            {slides.map((slide) => (
              <div
                key={slide.id}
                className="mr-[5.9701%] h-[400px] w-full max-w-[428px] flex-[0_0_100%] transform overflow-hidden rounded-6xl first:mr-[5.9701%] md:mr-[7.4074%] first:md:mr-[7.4074%] lg:h-[500px] lg:max-w-[784px]"
              >
                <img src={slide.image} alt={slide.alt} className="h-full w-full object-cover" />
              </div>
            ))}
          </SpacesCarousel>
        </div>
      </div>
    </>
  );
}
