export type speakers = {
  index: number;
  name: string;
  jobTitle: string;
  employer: string;
  image: string;
  bio: string;
  checked?: boolean;
};

export const speakers: speakers[] = [
  {
    index: 0,
    name: 'Michael Owolabi',
    jobTitle: 'CTO',
    employer: 'Spleet',
    bio: 'Michael is an experienced Software Engineer with 5+ years of experience in developing innovative solutions. He helps companies cut costs and increase revenue through improved software processes. He is also passionate about charity and human rights, volunteering with the United Nations.',
    image: 'https://sessionize.com/image/aef2-400o400o1-XwrGwNyHhV8C15Ve9hjp9A.png',
  },
  {
    index: 1,
    name: 'Echezona Agubata',
    jobTitle: 'CTO',
    employer: 'Coronation Merchant Bank',
    bio: 'Echezona is the CTO at Coronation Merchant Bank, developing IT strategy and leading technology teams. Previously at Union Bank and GTBank, he is known for Zero Downtime, Simplified innovation, and Fanatic support processes. He provides consult in IT Strategy, Service Management, and Governance.',
    image: 'https://sessionize.com/image/fea9-400o400o1-VrYfj95QGvT8vAhjpM84wa.jpg',
  },
  {
    index: 2,
    name: 'Daniel Benjamin',
    jobTitle: 'Software Engineer',
    employer: '',
    bio: 'Daniel is a fun guy that occasionally build software.',
    image: 'https://sessionize.com/image/55b2-400o400o1-wvvfEb4WrrCEKismRvVLJG.jpg',
  },
  {
    index: 3,
    name: 'Daniel Adeboye',
    jobTitle: 'Developer Relations Engineer & Software Engineer',
    employer: '',
    bio: 'Daniel is a Software Engineer and DevRel with 4+ years experience. He built Gitsecure and Wasps.dev, AI-powered tools for code security and review. He helps developers build better software through technical writing and community engagement.',
    image: 'https://sessionize.com/image/b965-400o400o1-7fGxH9EFFp3QBg4qzMC26g.jpg',
  },
  {
    index: 4,
    name: 'Olakunle Dosunmu',
    jobTitle: 'Senior Backend Engineer',
    employer: 'ETranzact Global',
    bio: 'Olakunle is a Senior Backend Engineer at Etranzact Global with 8+ years experience in scalable APIs and microservices. He specializes in fintech solutions that power digital payments across Africa.',
    image: 'https://sessionize.com/image/33cf-400o400o1-HGGzsyjUH6KBnQzYvYu88D.jpg',
  },
  {
    index: 5,
    name: 'Betty Alagwu',
    jobTitle: 'Full stack Software Engineer',
    employer: 'Mono',
    bio: 'Full stack software engineer at Mono, the fintech Plaid for African businesses. 3 years of professional software engineering experience, open source enthusiast, and previously a product manager for an open source startup.',
    image: 'https://sessionize.com/image/e3fb-400o400o1-JcvDcEKDz7RUuFfHGRwSj8.jpg',
  },
  {
    index: 6,
    name: 'Favour Onuoha',
    jobTitle: 'Senior Developer Relations Engineer',
    employer: 'Swing Finance',
    bio: "I am a Senior Developer Relations Engineer at Swing Finance with over 6 years of professional experience in the tech ecosystem. I'm also a Content Creator at X, Technical Writer at FreeCodeCamp, and a Fullstack Blockchain Developer.",
    image: 'https://sessionize.com/image/a051-400o400o1-XbkZrXFQt34fN7tToqmD14.png',
  },
  {
    index: 7,
    name: 'Oluwatimilehin Samuel Alapakristi',
    jobTitle: 'Senior Software Engineer',
    employer: 'OnePipe.io',
    bio: 'Oluwatimilehin is a Senior Software Engineer with extensive experience in Fintech, EdTech, Health Tech, eCommerce, and Logistics. He leads engineering teams, delivers cutting-edge solutions, and excels in solving complex challenges while collaborating with cross-functional teams.',
    image: 'https://sessionize.com/image/ddda-400o400o1-H9njas5S5sVpQm2d55gdvW.jpg',
  },
  {
    index: 8,
    name: 'Funke Olasupo',
    jobTitle: 'Technical Writer',
    employer: 'Rocket.Chat',
    bio: 'Funke is a seasoned technical writer at Rocket.Chat, producing clear user and developer documentation. She has worked with OpenFoodFacts and Macrometa, and contributes to Twillio, Honeybadger, and ButterCMS. She co-organizes developer and women-in-tech conferences through Google Developer Groups.',
    image: 'https://sessionize.com/image/40bf-400o400o1-SF1tsYnBuGx46FjM2Pbwc.jpg',
  },
  {
    index: 9,
    name: 'Daniel Anomfueme',
    jobTitle: 'Founder, DeSci Africa; Community Builder, VitaDAO',
    employer: 'DeSci Africa / VitaDAO',
    image: 'https://sessionize.com/image/db01-400o400o1-Bk8yFy6a3e2H6WHAQAeR8J.png',
    bio: 'For almost four years, Daniel Anomfueme has been an active builder of several Tech and Non-Tech Communities. He is currently exploring the possibilities of Decentralized Science as a contributor at VitaDAO and he recently started DeSci Africa to create awareness of DeSci in Africa.',
  },
  {
    index: 10,
    name: 'Abimbola Bajomo',
    jobTitle: 'Lead Product Manager',
    employer: 'Remita Payment Services Limited',
    image: 'https://sessionize.com/image/2696-400o400o1-J6cQ1tdFe5jPwYwvfEmAbv.jpg',
    bio: 'Abimbola is a Product Manager at Remita with 7+ years experience. She leads the Collections Product Suite and founded Product Talkative to help tech professionals unlock new opportunities.',
  },
  {
    index: 11,
    name: 'Justice Anaba',
    jobTitle: 'Brand Product Designer',
    employer: 'SeamlessHR',
    image: 'https://sessionize.com/image/7878-400o400o1-fQsG4SKtJumMo1ZnWboBEm.jpg',
    bio: 'A multifaceted creative leader, Justice blends engineering, design, and digital marketing with over 11 years of experience creating impactful brand solutions in competitive markets.',
  },
  {
    index: 12,
    name: 'Michael Mekuleyi',
    jobTitle: 'Senior DevOps Engineer',
    employer: 'Yassir',
    image: 'https://sessionize.com/image/33da-400o400o1-PC73Vaadgkjuqf67k1oBzr.jpeg',
    bio: 'Michael Mekuleyi is a DevOps Engineer, Google Developer Expert, and AWS Community Builder with a passion for SRE, Google Cloud, and Flutter. Outside work, he enjoys music and trying new recipes.',
  },
  {
    index: 13,
    name: 'Samuel Abada',
    jobTitle: 'Google Developer Expert, Flutter & Dart',
    employer: 'Shuttlers Mobility',
    image: 'https://sessionize.com/image/2e65-400o400o1-aUVsgQJAGE1aarDyjt5fk8.png',
    bio: 'Samuel is a GDE for Flutter and Dart, leading mobile engineering at Shuttlers. He co-organizes Flutter communities and GDG Akure, and is passionate about open-source, dev tools, and anime.',
  },
  {
    index: 14,
    name: 'Pratham Kumar',
    jobTitle: 'Developer Relations Manager',
    employer: 'APILayer',
    image: 'https://sessionize.com/image/3c06-400o400o1-HptYvC813pJbHCGw8TF2Fh.jpg',
    bio: 'Pratham is a DevRel who built a 450K+ developer community across social platforms, showcasing the power of community-driven engagement in tech.',
  },
  {
    index: 15,
    name: 'Joshua Onyeuche',
    jobTitle: 'Software Engineer',
    employer: 'Emergency Response Africa',
    image: 'https://sessionize.com/image/957d-400o400o1-9nV38VcaX6UwPYXyKaGRfB.png',
    bio: 'Joshua builds performant web interfaces and leads dev initiatives across fintech and healthtech. Creator of Frontend Bistro, he advocates for great UX, DX, and frontend-backend collaboration.',
  },
  {
    index: 16,
    name: 'Nwaamaka Iduwe',
    jobTitle: 'Business Intelligence Analyst',
    employer: 'Freelance',
    image: 'https://sessionize.com/image/cecc-400o400o1-N1z7UVmC79BSz8W46bMhFD.jpg',
    bio: "Nwaamaka designs interactive Power BI dashboards and simplifies technical insights. She's co-authored ML research and is passionate about APIs, data storytelling, and data mentorship.",
  },
  {
    index: 17,
    name: 'Mustapha Rufai',
    jobTitle: 'Software Engineer',
    employer: '',
    image: 'https://sessionize.com/image/3586-400o400o1-7FwyWgdVtgzRukfdLpRRvQ.jpg',
    bio: 'Mustapha is a software engineer focused on dev education and community. He previously led developer engagement at Paga and produces content for LinkedIn Learning and Pluralsight.',
  },
  {
    index: 18,
    name: 'Chisom Uma',
    jobTitle: 'Technical Writer and Marketing Manager',
    employer: 'Hamari Labs',
    image: 'https://sessionize.com/image/1421-400o400o1-VyGD8PvnDmdHDsvHxh5cyw.jpg',
    bio: 'Chisom is a seasoned technical writer and docs engineer, contributing to open-source projects like NGINX. He advocates for documentation as a product and supports open-source communities.',
  },
  {
    index: 19,
    name: 'Ademola Adelekan',
    jobTitle: 'Head of DevOps Engineering',
    employer: 'Interswitch (INDECO)',
    image: 'https://sessionize.com/image/7818-400o400o1-GfBbFWH9C6gKowtVDyb5WC.jpg',
    bio: 'Ademola Adelekan builds secure, scalable platforms and leads DevOps at Interswitch. With deep technical experience, he champions engineering productivity and reliability across teams.',
  },
  {
    index: 20,
    name: 'Nelson Isioma',
    jobTitle: 'Technical Writer',
    employer: 'PHPArch / Organizer, PHPxLagos',
    image: 'https://sessionize.com/image/39af-400o400o1-Q7NeUGogC3hnYrph6End3C.jpg',
    bio: 'Nelson is a technical writer at PHPArch and organizes PHPxLagos. He focuses on PHP development, open-source, and empowering the local dev ecosystem through documentation.',
  },
  {
    index: 21,
    name: 'Kimberly Samugana',
    jobTitle: 'API Partnership Manager',
    employer: 'MyCover.ai',
    image: 'https://sessionize.com/image/112f-400o400o1-pnQcWkpTkTjkr7Acp58e28.jpg',
    bio: "Kimberly manages API partnerships at MyCover.ai, enabling integrations with 40+ African tech companies. She's an advocate for inclusive insurance solutions and active in tech communities.",
  },
  {
    index: 22,
    name: 'Ibiniyi Obikoya',
    jobTitle: 'Tech Lead',
    employer: 'Korapay',
    image: 'https://sessionize.com/image/f891-400o400o1-Qc8tA3B2PfU1Fh19Ndptu9.jpg',
    bio: "Ibiniyi leads the MPT team at Korapay, building scalable financial APIs. A mentor and community convener, he's passionate about backend engineering, platform reliability, and tech-faith integration.",
  },
  {
    index: 23,
    name: 'Onome Owah',
    jobTitle: 'Software Developer',
    employer: 'Allstate Northern Ireland',
    image: 'https://sessionize.com/image/5373-400o400o1-46LSQi4Rnj4fvqVZUwAjeq.jpg',
    bio: 'Onome is a software developer at Allstate NI specializing in API performance optimization. She reengineered APIs to improve response times dramatically and is passionate about scalable backend systems.',
  },
  {
    index: 24,
    name: 'Simi Oluwatomi',
    jobTitle: 'Tech Lead | Software Developer | Cloud Developer | Community Builder',
    employer: '',
    image: 'https://sessionize.com/image/0332-400o400o1-pxWjThhGgQpJGt4uM7cXW8.jpg',
    bio: "Simi Oluwatomi is a back-end developer with experience in the fintech and healthcare industry with a proven track record of designing and implementing scalable and secure software solutions that enable organizations to improve their operations and enhance their customers' experience.",
  },
  {
    index: 25,
    name: 'Atuoha Anthony',
    jobTitle: 'Mobile Software Engineer',
    employer: '',
    image: 'https://sessionize.com/image/00ae-400o400o1-TqPo1WYzGT82z439JvzrvF.jpeg',
    bio: 'Mobile Software Engineer specializing in Flutter/Dart, Kotlin (Jetpack Compose), Swift & SwiftUI, with a comprehensive background in web technologies. Skilled in designing, developing, and deploying software for Android, iOS, Web, and other platforms. Adept at collaborating effectively with cross-functional teams to create high-quality, scalable products.',
  },
  {
    index: 26,
    name: 'Alexander Garuba',
    jobTitle: 'CTO',
    employer: 'Money Africa',
    image: 'https://sessionize.com/image/050a-400o400o1-3eX3BsEgEZVjeYjgdSE4Dy.jpg',
    bio: 'Alexander Garuba is a highly motivated and versatile full-stack developer with a proven track record of delivering robust, scalable, and maintainable software solutions. He is currently the Chief Technology Officer at Money Africa, with past roles at commercetools, AREA 17, GENEO Software, Reliance HMO, HotelsNG, and Decagon.',
  },
  {
    index: 27,
    name: 'Anthony Alaribe',
    jobTitle: 'Cofounder',
    employer: 'APItoolkit',
    image: 'https://sessionize.com/image/9770-400o400o1-WfTyAJfTM7wuszUkyDrNdU.jpg',
    bio: 'Anthony has spent over a decade building software at companies like Opera, Parity (Polkadot), and DeliveryHero. He founded APItoolkit.io to help companies avoid backend and API-related issues after losing $2M in orders due to such incidents.',
  },
  {
    index: 28,
    name: 'Fehintoluwa Dahunsi',
    jobTitle: 'Senior Software Engineer, Professional Cloud Architect',
    employer: 'Andela',
    image: 'https://sessionize.com/image/64dc-400o400o1-hKEA62cv9jA7KxZDdb1btZ.jpg',
    bio: 'Fehintoluwa Dahunsi is a distinguished Senior Software Developer in Test with expertise in test automation, DevOps, and CI/CD. His sessions are engaging, insightful, and packed with actionable takeaways for enhancing DevOps skills.',
  },
  {
    index: 29,
    name: 'Emmanuel Odianosen',
    jobTitle: 'Developer Relations',
    employer: 'Somnia Blockchain',
    image: 'https://sessionize.com/image/7182-400o400o1-EPn5dRMaQUGB2KTZZTm4q.jpg',
    bio: 'Emmanuel Odianosen is a Developer Relations Engineer at Fuse Blockchain. He is also a developer community organizer and technical writer focused on helping others grow in Web3.',
  },
  {
    index: 30,
    name: 'Solomon Olalemi',
    jobTitle: 'Product Manager',
    employer: 'Polaris Bank',
    image: 'https://sessionize.com/image/fe8f-400o400o1-BW55yQhDwpjPCPquyHFcmk.jpg',
    bio: 'Solomon Olalemi is a seasoned product manager with 6+ years of experience, currently at Polaris Bank. He led remittance and cryptocurrency infrastructure projects and guided Polaris Bank to win Digital Bank of the Year for three years.',
  },
  {
    index: 31,
    name: 'Paul Adams',
    jobTitle: 'Senior Integrations Engineer',
    employer: 'involve.me',
    image: 'https://sessionize.com/image/04bf-400o400o1-RP1vR6oHWKEKGvEQN6u4x4.jpg',
    bio: 'Paul Adams Ohiani is a Senior Software Developer at involve.me. Formerly the CTO of Selar.co, he has a passion for building scalable and impactful software products.',
  },
  {
    index: 32,
    name: 'Auwal MS',
    jobTitle: 'Software Engineering & Developer Relations',
    employer: '',
    image:
      'https://sessionize.com/image/0e7e-400o400o1-61-7959-4bf2-975a-380e1d0ea411.b022f2c0-ddf9-4eaf-b594-04697046f112.JPG',
    bio: 'Auwal MS is a software engineer with extensive experience across platforms. He actively contributes to Developer Relations, supporting developer communities and promoting innovative technology.',
  },
  {
    index: 33,
    name: 'Oluwaseun Dabiri',
    jobTitle: 'Product Architect | Product Manager',
    employer: 'MyCover.ai',
    image: 'https://sessionize.com/image/581a-400o400o1-3SmhRuFoG1ALc4zoc4cCU7.jpg',
    bio: 'Oluwaseun is a multi-talented professional blending product management, software engineering, and music technology. At MyCover.ai, he builds insurtech solutions and leads a federal initiative training 3 million tech talents in Nigeria.',
  },
  {
    index: 34,
    name: 'Favour Oriabure',
    jobTitle: 'Technical Architect',
    employer: 'SeamlessHR',
    image: 'https://sessionize.com/image/083b-400o400o1-Ey92rTxsg5YWAW4YWn65m2.jpg',
    bio: 'Favour Oriabure is a seasoned technical architect with 5+ years of experience in the payroll domain. He leads the design of scalable payroll, payments, and credit systems at SeamlessHR.',
  },
  {
    index: 35,
    name: 'Glory Olamigoke',
    jobTitle:
      'Product Manager, Core Banking Platform, Kuda. (Also Founder, TekNexus Africa and Co-Founder Tech Revolution Africa)',
    employer: 'Kuda',
    image: 'https://sessionize.com/image/05bd-400o400o1-waXdiAZSvaNoBToDjbfqwn.png',
    bio: 'Glory is a technology leader with 7+ years building global products. At Kuda, he manages core banking products. He founded TekNexus Africa, mentoring 5000+ African talents, and Tech Revolution Africa. He has partnered with MTN, CChub, and others, and is a published author and speaker.',
  },
  {
    index: 36,
    name: 'Kenneth Ezukwoke',
    jobTitle: 'Datategy, Lead Data Scientist-GenAI R&D',
    employer: 'Datategy',
    image: 'https://sessionize.com/image/d459-400o400o1-nAN3gaWXA6C14MFiNvsJB5.jpg',
    bio: `Kenneth is a Lead Data Scientist at Datategy, working on papAI-GenAI and computer vision projects. He holds a Ph.D in Applied Mathematics-GenAI, focusing on AI for Failure Analysis in Semiconductor Industry 4.0, collaborating with STMicroelectronics, Bosch, and Infineon AG.`,
  },
  {
    index: 37,
    name: 'Mfonobong Umondia',
    jobTitle: 'Community Manager & Technical Writer',
    employer: '',
    image: 'https://sessionize.com/image/0b51-400o400o1-a7jLJrwoSTi8qfU9PZNPgV.png',
    bio: 'Mfonobong is a Community Manager with 6+ years experience in design and developer spaces. She combines technical writing and Golang programming with strategic community building.',
  },
  {
    index: 38,
    name: 'Aminat Fowoke Balogun',
    jobTitle: 'Technical Product Manager, Milsat Technologies',
    employer: 'Milsat Technologies',
    image: 'https://sessionize.com/image/3893-400o400o1-Q5gS8UN9gTHWLgPMs36PCv.jpg',
    bio: 'Aminat is a Technical Product Manager at Milsat Technologies, leading geospatial solutions for national projects. She collaborates with government agencies to solve real-world problems through innovative technology.',
  },
  {
    index: 39,
    name: 'Chukwuemeka Chukwurah',
    jobTitle: 'Senior Software Engineer, Rocksteady Technologies',
    employer: 'Rocksteady Technologies',
    image: 'https://sessionize.com/image/404a-400o400o1-pTSSquNwXhsZry5mRAtBUs.jpg',
    bio: 'Chukwuemeka is a Senior Software Engineer with 7 years experience in distributed systems. At Risevest, he delivered products serving millions of users. He organizes GDG Cloud Lagos and mentors developers.',
  },
  {
    index: 40,
    name: 'Ijeoma Eti',
    jobTitle: 'Building Secure APIs',
    employer: '',
    image: 'https://sessionize.com/image/977d-400o400o1-WE7pdDNDHqGxr9VSA75Weq.jpg',
    bio: 'Ijeoma is a backend engineer focused on building APIs and solving complex challenges. She contributes to open-source projects like Layer5 Meshery and enjoys learning new skills like German.',
  },
  {
    index: 41,
    name: 'Olamide Ilori',
    jobTitle: 'Lead Frontend Engineer - Prospa YC (W21)',
    employer: 'Prospa',
    image: 'https://sessionize.com/image/0342-400o400o1-h8j9isbEvjeMFVi73rc2th.png',
    bio: 'Olamide is a Frontend Engineer specializing in scalable code and performance optimization. He mentors developers, conducts technical interviews, and speaks at conferences to empower tech teams.',
  },
  {
    index: 42,
    name: 'Jamiu Okanlawon',
    jobTitle: 'Mobile Engineer at OneRoof | Organizer of the FlutterBytes Conference',
    employer: 'OneRoof',
    image: 'https://sessionize.com/image/fe6b-400o400o1-PNWJMi6rDGe9JvdqHJZ6yC.jpg',
    bio: "Jamiu is a Mobile Engineer at OneRoof with 6 years experience, including 4 years in Flutter. He founded FlutterBytes Community and organizes Africa's largest Flutter conference.",
  },
  {
    index: 43,
    name: 'Kenechukwu Ozordi',
    jobTitle: 'Software Engineer, GTBank',
    employer: 'GTBank',
    image: 'https://sessionize.com/image/e5af-400o400o1-pYBBzneR1NbcwDbn32kYx4.jpg',
    bio: 'Ozordi is a Software Engineer specializing in backend development and API design. He builds scalable RESTful APIs and improves developer experience through clear documentation.',
  },
];
