export type speakers = {
  index: number;
  name: string;
  jobTitle: string;
  employer: string;
  image: string;
  bio: string;
  checked?: boolean;
  sessionFormat: string;
};

export const speakers: speakers[] = [
  {
    index: 0,
    name: 'Mehdi Medjaoui',
    jobTitle: 'Author of continuous API management',
    employer: 'Founder of APIDAYS',
    bio: 'keynote',
    image: '/Mehdi-Medjaoui.webp',
    sessionFormat: 'Keynote',
  },
  {
    index: 1,
    name: 'Michael Owolabi',
    jobTitle: 'CTO',
    employer: 'Spleet',
    bio: 'Building to last',
    image: 'https://sessionize.com/image/aef2-400o400o1-XwrGwNyHhV8C15Ve9hjp9A.png',
    sessionFormat: 'Keynote',
  },
  {
    index: 2,
    name: 'Chisom Uma',
    jobTitle: 'Technical Writer and Marketing Manager',
    employer: 'Hamari Labs',
    bio: 'From Frustration to Flow: Creating API Documentation Developers Actually Love',
    image: 'https://sessionize.com/image/1421-400o400o1-VyGD8PvnDmdHDsvHxh5cyw.jpg',
    sessionFormat: 'Keynote',
  },
  {
    index: 3,
    name: 'Ademola Adelekan',
    jobTitle: 'Head of DevOps Engineering',
    employer: 'Interswitch (INDECO)',
    bio: 'DevOps Meets APIs: Building, Governing, & Scaling API-First Architectures for Enterprise Application',
    image: 'https://sessionize.com/image/7818-400o400o1-GfBbFWH9C6gKowtVDyb5WC.jpg',
    sessionFormat: 'Keynote',
  },
  {
    index: 4,
    name: 'Echezona Agubata',
    jobTitle: 'CTO',
    employer: 'Coronation Merchant Bank',
    bio: 'API Architecture',
    image: 'https://sessionize.com/image/fea9-400o400o1-VrYfj95QGvT8vAhjpM84wa.jpg',
    sessionFormat: 'Lightning talk',
  },
  {
    index: 5,
    name: 'Daniel Benjamin',
    jobTitle: 'Software Engineer',
    employer: '',
    bio: 'Building APIs on cloudflare',
    image: 'https://sessionize.com/image/55b2-400o400o1-wvvfEb4WrrCEKismRvVLJG.jpg',
    sessionFormat: 'Lightning talk',
  },
  {
    index: 6,
    name: 'Daniel Anomfueme',
    jobTitle: 'Founder, DeSci Africa; Community Builder, VitaDAO',
    employer: 'DeSci Africa / VitaDAO',
    bio: 'API Security in Web3: Protecting Decentralized Applications from Common Threats',
    image: '/speakers/daniel.jpeg',
    sessionFormat: 'Lightning talk',
  },
  {
    index: 7,
    name: 'Nelson Isioma',
    jobTitle: 'Technical Writer',
    employer: 'PHPArch / Organizer, PHPxLagos',
    bio: 'Caching Strategies for High-Traffic APIs',
    image: 'https://sessionize.com/image/39af-400o400o1-Q7NeUGogC3hnYrph6End3C.jpg',
    sessionFormat: 'Lightning talk',
  },
  {
    index: 8,
    name: 'Kimberly Samugana',
    jobTitle: 'API Partnership Manager',
    employer: 'MyCover.ai',
    bio: 'Embedded Insurance in 5 Minutes',
    image: 'https://sessionize.com/image/112f-400o400o1-pnQcWkpTkTjkr7Acp58e28.jpg',
    sessionFormat: 'Lightning talk',
  },
  {
    index: 9,
    name: 'Paul Adams',
    jobTitle: 'Senior Integrations Engineer',
    employer: 'involve.me',
    bio: 'How we monitor and maintain over 40 third party integrations at involve.me',
    image: 'https://sessionize.com/image/04bf-400o400o1-RP1vR6oHWKEKGvEQN6u4x4.jpg',
    sessionFormat: 'Lightning talk',
  },
  {
    index: 10,
    name: 'Daniel Adeboye',
    jobTitle: 'Developer Relations Engineer & Software Engineer',
    employer: '',
    bio: 'API-first DevOps: Automating API deployments for speed and scale',
    image: 'https://sessionize.com/image/b965-400o400o1-7fGxH9EFFp3QBg4qzMC26g.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 11,
    name: 'Olakunle Dosunmu',
    jobTitle: 'Senior Backend Engineer',
    employer: 'ETranzact Global',
    bio: 'Autonomous APIs: Can APIs Self-Heal and Self-Optimize?',
    image: 'https://sessionize.com/image/33cf-400o400o1-HGGzsyjUH6KBnQzYvYu88D.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 12,
    name: 'Betty Alagwu',
    jobTitle: 'Full stack Software Engineer',
    employer: 'Mono',
    bio: 'API Engineering at Mono: Scaling Microservices to Handle Millions of Requests per Month',
    image: 'https://sessionize.com/image/e3fb-400o400o1-JcvDcEKDz7RUuFfHGRwSj8.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 13,
    name: 'Abimbola Bajomo',
    jobTitle: 'Lead Product Manager',
    employer: 'Remita Payment Services Limited',
    bio: 'Next-Gen API as a Service: AI-Driven Delivery, Adaptive Documentation, and Seamless Integration',
    image: 'https://sessionize.com/image/2696-400o400o1-J6cQ1tdFe5jPwYwvfEmAbv.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 14,
    name: 'Justice Anaba',
    jobTitle: 'Brand Product Designer',
    employer: 'SeamlessHR',
    bio: 'Designing Seamless API Experiences: Integrating Product Design with API Innovation',
    image: 'https://sessionize.com/image/7878-400o400o1-fQsG4SKtJumMo1ZnWboBEm.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 15,
    name: 'Pratham Kumar',
    jobTitle: 'Developer Relations Manager',
    employer: 'APILayer',
    bio: 'AI-driven HATEOAS',
    image: 'https://sessionize.com/image/3c06-400o400o1-HptYvC813pJbHCGw8TF2Fh.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 16,
    name: 'Joshua Onyeuche',
    jobTitle: 'Software Engineer',
    employer: 'Emergency Response Africa',
    bio: "Designing Developer-Friendly APIs: A Frontend Engineer's Wishlist",
    image: 'https://sessionize.com/image/957d-400o400o1-9nV38VcaX6UwPYXyKaGRfB.png',
    sessionFormat: 'Session',
  },
  {
    index: 17,
    name: 'Nwaamaka Iduwe',
    jobTitle: 'Business Intelligence Analyst',
    employer: 'Freelance',
    bio: "APIs Don't Speak — Dashboards Do",
    image: 'https://sessionize.com/image/cecc-400o400o1-N1z7UVmC79BSz8W46bMhFD.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 18,
    name: 'Mustapha Rufai',
    jobTitle: 'Software Engineer',
    employer: '',
    bio: 'Banking Without Banks? Building Resilient Wallet Infrastructure in Unstable Times',
    image: 'https://sessionize.com/image/3586-400o400o1-7FwyWgdVtgzRukfdLpRRvQ.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 19,
    name: 'Ibiniyi Obikoya',
    jobTitle: 'Tech Lead',
    employer: 'Korapay',
    bio: 'Building Resilient Microservice APIs: Engineering for High-Stakes Environments',
    image: 'https://sessionize.com/image/f891-400o400o1-Qc8tA3B2PfU1Fh19Ndptu9.jpg',
    sessionFormat: 'Session',
  },
  // {
  //   index: 20,
  //   name: 'Onome Owah',
  //   jobTitle: 'Software Developer',
  //   employer: 'Allstate Northern Ireland',
  //   bio: 'From Sluggish to Seamless: Optimizing API Performance',
  //   image: 'https://sessionize.com/image/5373-400o400o1-46LSQi4Rnj4fvqVZUwAjeq.jpg',
  //   sessionFormat: 'Session',
  // },
  {
    index: 21,
    name: 'Simi Oluwatomi',
    jobTitle: 'Tech Lead | Software Developer | Cloud Developer | Community Builder',
    employer: '',
    bio: "From Chaos to Clarity: Building API Integrations That Don't Burn Out Your Team or Product",
    image: 'https://sessionize.com/image/0332-400o400o1-pxWjThhGgQpJGt4uM7cXW8.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 22,
    name: 'Atuoha Anthony',
    jobTitle: 'Mobile Software Engineer',
    employer: '',
    bio: 'Beyond API Keys: Advanced Strategies for Securing Mobile API Integrations',
    image: '/speakers/atuoha.jpeg',
    sessionFormat: 'Session',
  },
  {
    index: 23,
    name: 'Alexander Garuba',
    jobTitle: 'CTO',
    employer: 'Money Africa',
    bio: 'Detecting threats and anomalies in API traffic with AI models.',
    image: 'https://sessionize.com/image/050a-400o400o1-3eX3BsEgEZVjeYjgdSE4Dy.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 24,
    name: 'Anthony Alaribe',
    jobTitle: 'Cofounder',
    employer: 'APItoolkit',
    bio: 'Detecting the Undetectable: Applying Merkle Trees and LLMs to Software Monitoring',
    image: 'https://sessionize.com/image/9770-400o400o1-WfTyAJfTM7wuszUkyDrNdU.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 25,
    name: 'Auwal MS',
    jobTitle: 'Software Engineering & Developer Relations',
    employer: '',
    bio: 'The Art and Science of Lovable API Documentation: Lessons from the Monnify Revamp',
    image:
      'https://sessionize.com/image/0e7e-400o400o1-61-7959-4bf2-975a-380e1d0ea411.b022f2c0-ddf9-4eaf-b594-04697046f112.JPG',
    sessionFormat: 'Session',
  },
  {
    index: 26,
    name: 'Oluwaseun Dabiri',
    jobTitle: 'Product Architect | Product Manager',
    employer: 'MyCover.ai',
    bio: "API-Driven Innovation: MyCover.ai's Blueprint for Modernizing Insurance Ecosystems",
    image: 'https://sessionize.com/image/581a-400o400o1-3SmhRuFoG1ALc4zoc4cCU7.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 27,
    name: 'Favour Oriabure',
    jobTitle: 'Technical Architect',
    employer: 'SeamlessHR',
    bio: 'Scaling Payroll Across Africa',
    image: 'https://sessionize.com/image/083b-400o400o1-Ey92rTxsg5YWAW4YWn65m2.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 28,
    name: 'Glory Olamigoke',
    jobTitle:
      'Product Manager, Core Banking Platform, Kuda. (Also Founder, TekNexus Africa and Co-Founder Tech Revolution Africa)',
    employer: 'Kuda',
    bio: 'Microservices Architecture 101: Principles and Best Practices',
    image: 'https://sessionize.com/image/05bd-400o400o1-waXdiAZSvaNoBToDjbfqwn.png',
    sessionFormat: 'Session',
  },
  {
    index: 29,
    name: 'Kenneth Ezukwoke',
    jobTitle: 'Datategy, Lead Data Scientist-GenAI R&D',
    employer: 'Datategy',
    bio: 'Shaping the future of semiconductor manufacturing with GenAI',
    image: 'https://sessionize.com/image/d459-400o400o1-nAN3gaWXA6C14MFiNvsJB5.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 30,
    name: 'Mfonobong Umondia',
    jobTitle: 'Community Manager & Technical Writer',
    employer: '',
    bio: 'How to design API Documentation that Technical & Non-technical Audience love',
    image: 'https://sessionize.com/image/0b51-400o400o1-a7jLJrwoSTi8qfU9PZNPgV.png',
    sessionFormat: 'Session',
  },
  {
    index: 31,
    name: 'Aminat Fowoke Balogun',
    jobTitle: 'Technical Product Manager, Milsat Technologies',
    employer: 'Milsat Technologies',
    bio: 'Mastering APIs as a Product Manager – Calling, Documenting, and Testing APIs',
    image: 'https://sessionize.com/image/3893-400o400o1-Q5gS8UN9gTHWLgPMs36PCv.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 32,
    name: 'Chukwuemeka Chukwurah',
    jobTitle: 'Senior Software Engineer, Rocksteady Technologies',
    employer: 'Rocksteady Technologies',
    bio: 'Securing The Fort: API Gateway Architectures, and why they matter',
    image: 'https://sessionize.com/image/404a-400o400o1-pTSSquNwXhsZry5mRAtBUs.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 33,
    name: 'Ijeoma Eti',
    jobTitle: 'Backend Engineer',
    employer: '',
    bio: 'Refactoring Legacy APIs with Domain-Driven Architecture',
    image: 'https://sessionize.com/image/977d-400o400o1-WE7pdDNDHqGxr9VSA75Weq.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 34,
    name: 'Olamide Ilori',
    jobTitle: 'Lead Frontend Engineer - Prospa YC (W21)',
    employer: 'Prospa',
    bio: "Why Your API is Making Frontend Developers' Lives Harder (And How to Fix It)",
    image: 'https://sessionize.com/image/0342-400o400o1-h8j9isbEvjeMFVi73rc2th.png',
    sessionFormat: 'Session',
  },
  {
    index: 35,
    name: 'Jamiu Okanlawon',
    jobTitle: 'Mobile Engineer at OneRoof | Organizer of the FlutterBytes Conference',
    employer: 'OneRoof',
    bio: 'Dart on the Server: Unlocking Full-Stack Potential',
    image: 'https://sessionize.com/image/fe6b-400o400o1-PNWJMi6rDGe9JvdqHJZ6yC.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 36,
    name: 'Kenechukwu Ozordi',
    jobTitle: 'Software Engineer, GTBank',
    employer: 'GTBank',
    bio: 'Redis in Action: From Simple Cache to Advanced Queues and Streams',
    image: 'https://sessionize.com/image/e5af-400o400o1-pYBBzneR1NbcwDbn32kYx4.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 37,
    name: 'Favour Onuoha',
    jobTitle: 'Senior Developer Relations Engineer',
    employer: 'Swing Finance',
    bio: 'Building an AI Documentation Agent for Your API using RAG',
    image: 'https://sessionize.com/image/a051-400o400o1-XbkZrXFQt34fN7tToqmD14.png',
    sessionFormat: 'Workshop',
  },
  {
    index: 38,
    name: 'Oluwatimilehin Samuel Alapakristi',
    jobTitle: 'Senior Software Engineer',
    employer: 'OnePipe.io',
    bio: 'API Specifications: Open Banking Specification',
    image: 'https://sessionize.com/image/ddda-400o400o1-H9njas5S5sVpQm2d55gdvW.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 39,
    name: 'Funke Olasupo',
    jobTitle: 'Technical Writer',
    employer: 'Rocket.Chat',
    bio: 'Getting Your OpenAPI Spec Ready for Code Generation',
    image: 'https://sessionize.com/image/40bf-400o400o1-SF1tsYnBuGx46FjM2Pbwc.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 40,
    name: 'Michael Mekuleyi',
    jobTitle: 'Senior DevOps Engineer',
    employer: 'Yassir',
    bio: 'Monitoring your APIs like a SuperHero with the Kubernetes prometheus stack',
    image: 'https://sessionize.com/image/33da-400o400o1-PC73Vaadgkjuqf67k1oBzr.jpeg',
    sessionFormat: 'Workshop',
  },
  {
    index: 41,
    name: 'Samuel Abada',
    jobTitle: 'Google Developer Expert, Flutter & Dart',
    employer: 'Shuttlers Mobility',
    bio: 'Server-Side Rendering with Dart: Building Dynamic Web Applications',
    image: 'https://sessionize.com/image/2e65-400o400o1-aUVsgQJAGE1aarDyjt5fk8.png',
    sessionFormat: 'Workshop',
  },
  {
    index: 42,
    name: 'Fehintoluwa Dahunsi',
    jobTitle: 'Senior Software Engineer, Professional Cloud Architect',
    employer: 'Andela',
    bio: 'Tested and Trusted : Building Testable APIs and Testing Testable APIs.',
    image: 'https://sessionize.com/image/64dc-400o400o1-hKEA62cv9jA7KxZDdb1btZ.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 43,
    name: 'Emmanuel Odianosen',
    jobTitle: 'Developer Relations',
    employer: 'Somnia Blockchain',
    bio: 'Leveraging Subgraph APIs for Real-Time Blockchain Data',
    image: 'https://sessionize.com/image/7182-400o400o1-EPn5dRMaQUGB2KTZZTm4q.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 44,
    name: 'Solomon Olalemi',
    jobTitle: 'Product Manager',
    employer: 'Polaris Bank',
    bio: 'From Vision to Execution: Building APIs as Scalable Products in Fintech',
    image: 'https://sessionize.com/image/fe8f-400o400o1-BW55yQhDwpjPCPquyHFcmk.jpg',
    sessionFormat: 'Workshop',
  },
];
