export type person = {
  index: number;
  name: string;
  jobTitle: string;
  employer: string;
  image: string;
  bio?: string;
  checked?: boolean;
  sessionFormat?: string;
};

export const speakers: person[] = [
  {
    index: 0,
    name: 'Chinedu Otutu',
    jobTitle: 'Software Engineer',
    employer: 'Greenplaces',
    bio: 'Type-Safe APIs with Hono and Zod: Fast, Lightweight, and Bulletproof',
    image: 'https://sessionize.com/image/b308-400o400o1-MLHQU6sWK7jieNedxaLCa.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 1,
    name: 'Prince Onyeanuna',
    jobTitle: 'Technical Writer',
    employer: 'Pi-Squared Inc',
    bio: 'The lazy way to keep your API Docs in sync',
    image: 'https://sessionize.com/image/253c-400o400o1-W4vHpv22qgYDJefzW5rMqH.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 2,
    name: 'Funke Olasupo',
    jobTitle: 'Technical Writer',
    employer: 'Rocket.Chat',
    bio: 'Your API Docs Are Breaking AI',
    image: 'https://sessionize.com/image/40bf-400o400o1-SF1tsYnBuGx46FjM2Pbwc.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 3,
    name: 'Ayooluwa Isaiah',
    jobTitle: 'Google Developer Expert (Web)',
    employer: '',
    bio: 'Monitoring APIs with OpenTelemetry',
    image: 'https://sessionize.com/image/7b03-400o400o1-wEBLRrqgnU8LvsNP7xcU3V.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 4,
    name: 'Alayesanmi Femi',
    jobTitle: 'Head of Engineering',
    employer: 'Mono',
    bio: 'Rethinking Caching: Building APIs For The Unpredictable Traffic from Agentic Systems',
    image: 'https://sessionize.com/image/0d54-400o400o1-GX3CZhjW8tLu3Q3QUJsyxQ.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 5,
    name: 'Jamiu Okanlawon',
    jobTitle: 'Developer Advocate',
    employer: 'Invertase | Organizer of the FlutterBytes Conference',
    bio: 'Building Your First AI Agent with Genkit',
    image: 'https://sessionize.com/image/fe6b-400o400o1-PNWJMi6rDGe9JvdqHJZ6yC.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 6,
    name: 'Tes Sal',
    jobTitle: 'Cybersecurity Specialist',
    employer: 'PureSec Agency',
    bio: 'Hacking APIs in the Wild: Finding, Exploiting & Reporting Modern API Vulnerabilities',
    image: 'https://sessionize.com/image/e651-400o400o1-efExz4h56S6hkXJUwtGJt.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 7,
    name: 'Abdulqudus Abubakre',
    jobTitle: 'Front end developer',
    employer: '',
    bio: 'From REST to MCP: Making Your Backend AI-Ready with FastMCP',
    image: 'https://sessionize.com/image/83a3-400o400o1-h3ZQRgGR7cXiLxDCs7J3DM.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 8,
    name: 'Usman Soliu',
    jobTitle: 'Technical Lead',
    employer: '',
    bio: 'From Monolith to Microservices: Designing Resilient, Observable APIs with Node.js',
    image: 'https://sessionize.com/image/708e-400o400o1-nzD53E988gWj2nX6oVcEHr.png',
    sessionFormat: 'Workshop',
  },
  {
    index: 9,
    name: 'Nasihudeen Jimoh',
    jobTitle: 'Developer Experience Engineer',
    employer: '',
    bio: 'Designing Better Developer Experience for Web3 APIs',
    image: 'https://sessionize.com/image/bdff-400o400o1-fyMuUUSxpKLNw946bLnz15.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 10,
    name: 'Ibukun Adedeji',
    jobTitle: 'Product Lead',
    employer: 'Moniepoint',
    bio: 'Where will it converge?',
    image: 'https://sessionize.com/image/e3e5-400o400o1-HrsduWbfojaSk6RXsPgq4p.jpg',
    sessionFormat: 'Lightning talk',
  },
  {
    index: 11,
    name: 'Obi Uchenna David',
    jobTitle: 'Associate Vice President, Engineering',
    employer: 'Cowrywise',
    bio: 'AI Agents Need Guardrails: Securing APIs in the Age of Autonomous Systems',
    image: 'https://sessionize.com/image/05b5-400o400o1-SFPYVWmFByt2kyqWGNoEXt.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 12,
    name: 'Onyedikachi Hope Amaechi-Okorie',
    jobTitle: 'Technical Community Advocate',
    employer: 'JSON Schema & AI Ethics Researcher, Aula Fellowship for AI Science, Tech, and Policy',
    bio: 'Improving API Adoption Through Developer Experience, Not Just Design',
    image: 'https://sessionize.com/image/7be1-400o400o1-MSc3G3yrMCgGBtfrCdaV81.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 13,
    name: 'Joel Olawanle',
    jobTitle: 'Software Engineer & Technical Writer',
    employer: '',
    bio: 'Software Is Going Headless: What the API Becomes When Agents Run Everything',
    image: 'https://sessionize.com/image/6053-400o400o1-YMfiJEdR4Koy2vgx6ijSog.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 14,
    name: 'Amarachi Iheanacho',
    jobTitle: 'Developer Advocate for Eyer',
    employer: '',
    bio: 'Governance Without the Bureaucracy: How to Enforce API Standards Without Slowing Down Your Team',
    image: 'https://sessionize.com/image/daf1-400o400o1-XmR8Mdn7DWryyU9Ta5LuJ9.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 15,
    name: 'Cindy Shontan',
    jobTitle: 'Lead Product Designer',
    employer: '',
    bio: 'Designing APIs as Products: How Product Thinking Improves Developer Experience',
    image: 'https://sessionize.com/image/9225-400o400o1-QG2hSL3U8JURic3SBWoL44.png',
    sessionFormat: 'Session',
  },
  {
    index: 16,
    name: 'Chigozie Madubuko',
    jobTitle: 'Team Lead, Senior Software Engineer',
    employer: 'Kora',
    bio: 'AI Can Write Code. But It Doesn’t Know Your System',
    image: 'https://sessionize.com/image/8226-400o400o1-3G7pvWMxceKaeBa4yxgcPF.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 17,
    name: 'Oluwatoni Akinmolayan',
    jobTitle: 'Senior Software Engineer',
    employer: 'Busha',
    bio: 'Building Compliant Fintech APIs for African Corridors',
    image: 'https://sessionize.com/image/8006-400o400o1-Qr6ySJGAnovkY8JYobDbit.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 18,
    name: 'Motunrayo Koyejo',
    jobTitle: 'Software Engineer',
    employer: '',
    bio: 'When Payments Fail: Designing Resilient APIs for Fintech Systems',
    image: 'https://sessionize.com/image/4306-400o400o1-Dn47GLqTWCN6bJWcgEamjG.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 19,
    name: 'Ifeanyi Echereobia',
    jobTitle: 'Technical Business Analyst',
    employer: 'Guaranty Trust Bank',
    bio: 'The APIs You Don’t Control: Building on NIBSS, CBN & Payment Rails Without Losing Your Mind',
    image: 'https://sessionize.com/image/b615-400o400o1-pCJzgH1op2ukZmSyHrd4Mi.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 20,
    name: 'Jamiu Adam',
    jobTitle: 'Senior Backend Engineer',
    employer: 'Deel',
    bio: 'When Your API Is Slow, It’s Probably SQL: Performance Tuning for Production APIs',
    image: 'https://sessionize.com/image/bdfc-400o400o1-QHyz6oP7QajryFhp7Z8DqU.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 21,
    name: 'Somtochi Onyekwere',
    jobTitle: 'Software Engineer',
    employer: 'Fly.io',
    bio: 'What API Designers Can Learn from the Kubernetes API',
    image: 'https://sessionize.com/image/2c9d-400o400o1-REPh3tvRTncr5K4aWDW125.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 22,
    name: 'Kelechi Oliver Azorji',
    jobTitle: 'Software Engineer',
    employer: '',
    bio: 'From Scattered Docs to Instant Answers: How We Built an Internal Knowledge Graph with LangChain',
    image: 'https://sessionize.com/image/82c9-400o400o1-HeDpGtAhHjdGR1LhEjEGdX.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 23,
    name: 'Progress Ochuko Eyaadah (Koxy)',
    jobTitle: 'Blockchain Engineer',
    employer: '',
    bio: 'Building Crypto Payment APIs in Africa: Stablecoins, On-Ramps & the Regulatory Tightrope',
    image: 'https://sessionize.com/image/3740-400o400o1-DMEyK4cyRS3hQUKdHDgT7C.jpg',
    sessionFormat: 'Session',
  },
  {
    index: 24,
    name: 'Peterson Nwoko',
    jobTitle: 'Senior Cloud Engineer',
    employer: 'Wolters Kluwer',
    bio: 'From Prompts to Autonomous Systems: Architecting Production-Ready AI Agents on Google Cloud',
    image: 'https://sessionize.com/image/3634-400o400o1-DTJHje4NZwykabHb4dtunh.jpg',
    sessionFormat: 'Keynote',
  },
  {
    index: 25,
    name: 'Ayomide Ariyo',
    jobTitle: 'Senior Software Engineer',
    employer: 'Selar',
    bio: 'The Assumptions That Break APIs in Production',
    image: 'https://sessionize.com/image/6caa-400o400o1-MmzkeKEdNGWvKHEUrXUmD3.jpg',
    sessionFormat: 'Lightning talk',
  },
  {
    index: 26,
    name: 'Timothy Ogunwemimo',
    jobTitle: 'Cloud Engineer',
    employer: 'Appspace',
    bio: 'Building Robust, Secure, and Scalable API Infrastructure with Microsoft Azure Services',
    image: 'https://cdn.sessionize.com/image/6674-400o400o1-BzUhJSwDN3TMdiAeJjAnHW.jpg',
    sessionFormat: 'Workshop',
  },
  {
    index: 27,
    name: 'Chilezie Unachukwu',
    jobTitle: 'Product Manager, WECA',
    employer: 'MTN-i',
    bio: "The Network Knows: Leveraging Telco Capabilities to Solve Fintech's Hardest Problems",
    image: '/speakers/chilezie-unachukwu.png',
    sessionFormat: 'Keynote',
  },
  {
    index: 28,
    name: 'Auwal MS',
    jobTitle: 'Software Engineering & Developer Relations',
    employer: 'Moniepoint',
    bio: 'Are Your APIs Ready for Agents',
    image: '/speakers/auwal-ms.jpg',
    sessionFormat: 'Keynote',
  },
];
